### ISSUE TITLE
Panic scanning image

### ISSUE THREAD

**Issue by tegioz** [aquasecurity/trivy#1004]
Hi! This is Sergio, from Artifact Hub 👋 

First, I'd like to thank you for your work on Trivy, it's really awesome! ❤️ 

## Description

We are experiencing a problem with Trivy while scanning certain images. Please find below an example, I can provide more images that trigger the error if needed.

```
$ trivy image quay.io/eclipse/che-plugin-sidecar@sha256:8615a29435b0256bffaf85ab2cf9327b059f14eaa6614346dfd51e3a6dd9f041
panic: runtime error: index out of range [1] with length 0

goroutine 4386 [running]:
github.com/aquasecurity/go-dep-parser/pkg/gomod.Parse(0x2518e20, 0xc0007df2f0, 0x6c70755474636570, 0x202c676b70202c65, 0x7474657270202c6e, 0x64090a297d6e7b79, 0x6e75662072656665)
	/home/runner/go/pkg/mod/github.com/aquasecurity/go-dep-parser@v0.0.0-20210427143403-3c97ccc53976/pkg/gomod/parse.go:23 +0x56f
github.com/aquasecurity/fanal/analyzer/library.Analyze(0x22e6a1b, 0x5, 0xc000fd9470, 0x2a, 0xc000bb5200, 0x153, 0x200, 0x234d078, 0x3d3d20646e694b2e, 0x6461422e74736120, ...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210501235003-c816628070c1/analyzer/library/analyze.go:18 +0x93
github.com/aquasecurity/fanal/analyzer/library/gomod.gomodAnalyzer.Analyze(0xc000fd9470, 0x2a, 0xc000bb5200, 0x153, 0x200, 0x202f2f0909090a7b, 0x20737463656a624f, 0x7520656874206e69)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210501235003-c816628070c1/analyzer/library/gomod/gomod.go:26 +0x95
github.com/aquasecurity/fanal/analyzer.Analyzer.AnalyzeFile.func1(0xc0000a0140, 0xc0003708e0, 0xc00017a7e0, 0x253b0c0, 0x2e56e30, 0xc000fd9470, 0x2a, 0xc000bb5200, 0x153, 0x200)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210501235003-c816628070c1/analyzer/analyzer.go:209 +0xb9
created by github.com/aquasecurity/fanal/analyzer.Analyzer.AnalyzeFile
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210501235003-c816628070c1/analyzer/analyzer.go:205 +0x2d1
```

## Additional details (base image name, container registry info...):

```
$ trivy --version
Version: 0.18.1
```

**Comment by knqyf263** [comment]
Thanks for the report! We'll have a look.

**Comment by knqyf263** [comment]
We've fixed this issue. It will be included in the next version.

**Comment by tegioz** [comment]
That's great! Thanks @knqyf263 🙂
