### ISSUE TITLE
Bug/Feature: Support Terraform git/ssh-modules

### ISSUE THREAD

**Issue by strowi** [aquasecurity/trivy#1126]
Hi,

happy about the terraform integration i fiddled around a little with our repositories.
I noticed a weird behavior with 0.19.1:

without a .terraform folder:
```
trivy config .
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-ec2-instance.git?ref=v2.19.0' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-bastion.git?ref=v2.2.2' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-alb.git?ref=v6.2.0' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-vpc.git?ref=v3.0.0' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-vpc.git//modules/vpc-endpoints?ref=v3.0.0' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-vpc.git?ref=v3.0.0' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-vpc.git//modules/vpc-endpoints?ref=v3.0.0' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-autoscaling.git?ref=v4.1.0' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::ssh://git@XYZ:2222/sys/mirror/terraform-aws-modules/terraform-aws-gitlab-runner.git?ref=4.25.0' -  try to 'terraform init' first
2021-07-16T17:41:11.772+0200  INFO  Detected config files: 35

../modules/common/ci_pubkey.tf (terraform)
==========================================
Tests: 1 (SUCCESSES: 1, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
...
```

after running terraform init:

```
trivy config .
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/security-group/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/acm/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
WARNING: Failed to load module: failed to load module cache: open /home/rvg/src/ck/sys/infra/aws/control_prod/.terraform/modules/runner/examples/runner-docker/modules/cache: no such file or directory
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
WARNING: Failed to load module: failed to load module cache: open /home/rvg/src/ck/sys/infra/aws/control_prod/.terraform/modules/runner/examples/runner-pre-registered/modules/cache: no such file or directory
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/vpc/aws' -  try to 'terraform init' first
WARNING: Failed to load module: failed to load module cache: open /home/rvg/src/ck/sys/infra/aws/control_prod/.terraform/modules/runner/examples/runner-public/modules/cache: no such file or directory
WARNING: Failed to load module: failed to load module cache: open /home/rvg/src/ck/sys/infra/aws/control_prod/.terraform/modules/runner/examples/runner-public/modules/cache: no such file or directory
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: skipped AWS049 r due to error(s): not a string
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x109bc18]

goroutine 1 [running]:
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan.func1(0xc00f91d670, 0xc000e9cf60, 0xc004e41020, 0xc00f91d690, 0xc00f91d6a8)
  /home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/internal/app/tfsec/scanner/scanner.go:65 +0xaf8
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan(0xc004e41020, 0xc003f38000, 0x166, 0x200, 0x0, 0x0, 0x0)
  /home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/internal/app/tfsec/scanner/scanner.go:81 +0x232
github.com/tfsec/tfsec/pkg/externalscan.(*ExternalScanner).Scan(0xc000472150, 0xc000287280, 0x40, 0x0, 0x0, 0x1)
  /home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/pkg/externalscan/external_scan.go:60 +0x231
github.com/aquasecurity/fanal/config/scanner.Scanner.scanTerraformByTFSec(0x7ffdf08911a8, 0x1, 0xc00012aca0, 0x2, 0x2, 0xc000d28300, 0xc000472150, 0xc0005bc000, 0x127, 0x200, ...)
  /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/config/scanner/scanner.go:115 +0x105
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs(0x7ffdf08911a8, 0x1, 0xc00012aca0, 0x2, 0x2, 0xc000d28300, 0xc000472150, 0x1d2ea78, 0xc000800fc0, 0xc000d48000, ...)
  /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/config/scanner/scanner.go:68 +0x34e
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect(0x7ffdf08911a8, 0x1, 0x7f243ff5def8, 0xc00007b350, 0xc000241600, 0x1e, 0x20, 0x0, 0x0, 0x0, ...)
  /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/artifact/local/fs.go:87 +0x378
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact(0x1d0a520, 0xc000d1d3c0, 0x1d0a380, 0xc000c37560, 0x1d2ea78, 0xc000800fc0, 0x0, 0x0, 0x0, 0xc00007b280, ...)
  /home/runner/work/trivy/trivy/pkg/scanner/scan.go:96 +0xb2
github.com/aquasecurity/trivy/pkg/commands/artifact.scan(0x1d2ea78, 0xc000800fc0, 0xc000802c40, 0xc000142468, 0x1cd4e60, 0x6, 0x0, 0xc00003e9d8, 0x16, 0x0, ...)
  /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:183 +0x658
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout(0x1d2ea78, 0xc000800fc0, 0xc000802c40, 0xc000142468, 0x1cd4e60, 0x6, 0x0, 0xc00003e9d8, 0x16, 0x0, ...)
  /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:67 +0x308
github.com/aquasecurity/trivy/pkg/commands/artifact.Run(0x1d2ea40, 0xc0001a0020, 0xc000802c40, 0xc000142468, 0x1cd4e60, 0x6, 0x0, 0xc00003e9d8, 0x16, 0x0, ...)
  /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:39 +0xf8
github.com/aquasecurity/trivy/pkg/commands/artifact.ConfigRun(0xc000802c40, 0x13, 0x24)
  /home/runner/work/trivy/trivy/pkg/commands/artifact/config.go:30 +0x2d6
github.com/urfave/cli/v2.(*Command).Run(0xc0000fcb40, 0xc000802500, 0x0, 0x0)
  /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc000190680, 0x1d2ea40, 0xc0001a0020, 0xc00018c000, 0x3, 0x3, 0x0, 0x0)
  /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
  /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
  /home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x87
```

regards,
strowi

**Comment by thaim** [comment]
I reproduced with another module.
Using trivy 0.19.2 and terraform-aws-modules/vpc/aws, similar error occured with same steps.

```
$ cat network.tf 
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
}

$ trivy conf .  
WARNING: Failed to load module: missing module with source 'terraform-aws-modules/s3-bucket/aws' -  try to 'terraform init' first
WARNING: skipped AWS049 r due to error(s): not a string
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1c9bc78]

goroutine 1 [running]:
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan.func1(0xc0036d9670, 0xc000bace28, 0xc0026dea80, 0xc0036d9690, 0xc0036d96a8)
	/home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/internal/app/tfsec/scanner/scanner.go:65 +0xaf8
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan(0xc0026dea80, 0xc0009a3000, 0x432, 0x500, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/internal/app/tfsec/scanner/scanner.go:81 +0x232
github.com/tfsec/tfsec/pkg/externalscan.(*ExternalScanner).Scan(0xc000074180, 0xc0007aae40, 0x31, 0x0, 0x0, 0x1)
	/home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/pkg/externalscan/external_scan.go:60 +0x231
github.com/aquasecurity/fanal/config/scanner.Scanner.scanTerraformByTFSec(0x7ffeefbffa2b, 0x1, 0xc000081d60, 0x2, 0x2, 0xc000998a00, 0xc000074180, 0xc0005dcc00, 0x32, 0x40, ...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210719144537-c73c1e9f21bf/config/scanner/scanner.go:115 +0x105
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs(0x7ffeefbffa2b, 0x1, 0xc000081d60, 0x2, 0x2, 0xc000998a00, 0xc000074180, 0x292edb8, 0xc00051cea0, 0xc0005dc000, ...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210719144537-c73c1e9f21bf/config/scanner/scanner.go:68 +0x34e
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect(0x7ffeefbffa2b, 0x1, 0xb5f4a98, 0xc00048ed30, 0xc000754600, 0x1e, 0x20, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210719144537-c73c1e9f21bf/artifact/local/fs.go:87 +0x378
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact(0x290a820, 0xc000bf0940, 0x290a680, 0xc00087d440, 0x292edb8, 0xc00051cea0, 0x0, 0x0, 0x0, 0xc00048ec70, ...)
	/home/runner/work/trivy/trivy/pkg/scanner/scan.go:96 +0xb2
github.com/aquasecurity/trivy/pkg/commands/artifact.scan(0x292edb8, 0xc00051cea0, 0xc0004d68c0, 0xc00012ca70, 0x28d4dc4, 0x6, 0x0, 0xc0004ca6c0, 0x21, 0x0, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:183 +0x658
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout(0x292edb8, 0xc00051cea0, 0xc0004d68c0, 0xc00012ca70, 0x28d4dc4, 0x6, 0x0, 0xc0004ca6c0, 0x21, 0x0, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:67 +0x308
github.com/aquasecurity/trivy/pkg/commands/artifact.Run(0x292ed80, 0xc000120008, 0xc0004d68c0, 0xc00012ca70, 0x28d4dc4, 0x6, 0x0, 0xc0004ca6c0, 0x21, 0x0, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:39 +0xf8
github.com/aquasecurity/trivy/pkg/commands/artifact.ConfigRun(0xc0004d68c0, 0x13, 0x24)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/config.go:30 +0x2d6
github.com/urfave/cli/v2.(*Command).Run(0xc00087c480, 0xc0004d6180, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc000122340, 0x292ed80, 0xc000120008, 0xc00011a090, 0x3, 0x3, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x87
```

**Comment by lghakamo-paf** [comment]
I'm able to reproduce the issue on our (internal) modules as well using trivy 0.19.2.

**Comment by knqyf263** [comment]
Thanks all. @AndreyLevchenko is working on this issue now.

**Comment by knqyf263** [comment]
v0.20.0 is out. Please let me know if you face the same issue again.
