### ISSUE TITLE
Error observed in TFSec when running Trivy in config scan mode

### ISSUE THREAD

**Issue by simar7** [aquasecurity/trivy#1193]
## Description

An error observed (along with a panic stack trace) while running the config scanner on a git repo.

Git repo in question: https://github.com/ministryofjustice/opg-lpa

The stack trace isn't actually a panic but purposely printed here: https://github.com/aquasecurity/tfsec/blob/master/pkg/rule/check.go#L24-L25

Running it locally I've not been able to experience it. Either it has been fixed since the last run or there's some other difference.

## What did you expect to happen?
No errors.

## What happened instead?
An error with a stack trace.
```
2021-08-20T13:13:55.1704340Z 2021-08-20T13:13:55.169Z	[34mINFO[0m	Need to update the built-in policies
2021-08-20T13:13:55.1705836Z 2021-08-20T13:13:55.170Z	[34mINFO[0m	Downloading the built-in policies...
2021-08-20T13:13:55.8032690Z WARNING: Failed to load module: missing module with source 'git@github.com:ministryofjustice/terraform-aws-moj-ip-whitelist.git' -  try to 'terraform init' first
2021-08-20T13:13:55.8515844Z WARNING: skipped AWS097 r due to error(s): not a string
2021-08-20T13:13:55.8550972Z panic: runtime error: invalid memory address or nil pointer dereference
2021-08-20T13:13:55.8551862Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x109c158]
2021-08-20T13:13:55.8552343Z 
2021-08-20T13:13:55.8552739Z goroutine 1 [running]:
2021-08-20T13:13:55.8553604Z github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan.func1(0xc000d5f670, 0xc0009a4e10, 0xc000952e60, 0xc000d5f690, 0xc000d5f6a8)
2021-08-20T13:13:55.8555567Z 	/home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/internal/app/tfsec/scanner/scanner.go:65 +0xaf8
2021-08-20T13:13:55.8556659Z github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan(0xc000952e60, 0xc000c09000, 0x140, 0x200, 0x0, 0x0, 0x0)
2021-08-20T13:13:55.8558030Z 	/home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/internal/app/tfsec/scanner/scanner.go:81 +0x232
2021-08-20T13:13:55.8559436Z github.com/tfsec/tfsec/pkg/externalscan.(*ExternalScanner).Scan(0xc0007b6900, 0xc00057a180, 0x1c, 0x0, 0x0, 0x1)
2021-08-20T13:13:55.8560883Z 	/home/runner/go/pkg/mod/github.com/tfsec/tfsec@v0.40.8-0.20210702100641-956c4f18a1b8/pkg/externalscan/external_scan.go:60 +0x231
2021-08-20T13:13:55.8562577Z github.com/aquasecurity/fanal/config/scanner.Scanner.scanTerraformByTFSec(0x7fffaecd602e, 0x17, 0xc000080140, 0x2, 0x2, 0xc0006a9900, 0xc0007b6900, 0xc000c99800, 0x28, 0x40, ...)
2021-08-20T13:13:55.8564665Z 	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210719144537-c73c1e9f21bf/config/scanner/scanner.go:115 +0x105
2021-08-20T13:13:55.8566082Z github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs(0x7fffaecd602e, 0x17, 0xc000080140, 0x2, 0x2, 0xc0006a9900, 0xc0007b6900, 0x1d2ead8, 0xc00011d860, 0xc000c98c00, ...)
2021-08-20T13:13:55.8568228Z 	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210719144537-c73c1e9f21bf/config/scanner/scanner.go:68 +0x34e
2021-08-20T13:13:55.8584659Z github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect(0x7fffaecd602e, 0x17, 0x7f0381f7c390, 0xc00040a660, 0xc000577000, 0x1e, 0x20, 0x0, 0x0, 0x0, ...)
2021-08-20T13:13:55.8586385Z 	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210719144537-c73c1e9f21bf/artifact/local/fs.go:87 +0x378
2021-08-20T13:13:55.8587998Z github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact(0x1d0a580, 0xc000b58f60, 0x1d0a3e0, 0xc000ae1e60, 0x1d2ead8, 0xc00011d860, 0x0, 0x0, 0x0, 0xc00040a590, ...)
2021-08-20T13:13:55.8589493Z 	/home/runner/work/trivy/trivy/pkg/scanner/scan.go:96 +0xb2
2021-08-20T13:13:55.8590674Z github.com/aquasecurity/trivy/pkg/commands/artifact.scan(0x1d2ead8, 0xc00011d860, 0xc00028ba80, 0xc00011aa98, 0x1cd4ec0, 0x6, 0x0, 0xc00003fa60, 0x19, 0x0, ...)
2021-08-20T13:13:55.8591714Z 	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:183 +0x658
2021-08-20T13:13:55.8593139Z github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout(0x1d2ead8, 0xc00011d860, 0xc00028ba80, 0xc00011aa98, 0x1cd4ec0, 0x6, 0x0, 0xc00003fa60, 0x19, 0x0, ...)
2021-08-20T13:13:55.8594445Z 	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:67 +0x308
2021-08-20T13:13:55.8595461Z github.com/aquasecurity/trivy/pkg/commands/artifact.Run(0x1d2eaa0, 0xc000116030, 0xc00028ba80, 0xc00011aa98, 0x1cd4ec0, 0x6, 0x0, 0xc00003fa60, 0x19, 0x0, ...)
2021-08-20T13:13:55.8596479Z 	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:39 +0xf8
2021-08-20T13:13:55.8597385Z github.com/aquasecurity/trivy/pkg/commands/artifact.ConfigRun(0xc00028ba80, 0x13, 0x24)
2021-08-20T13:13:55.8598602Z 	/home/runner/work/trivy/trivy/pkg/commands/artifact/config.go:30 +0x2d6
2021-08-20T13:13:55.8599551Z github.com/urfave/cli/v2.(*Command).Run(0xc0003fa360, 0xc00028afc0, 0x0, 0x0)
2021-08-20T13:13:55.8600342Z 	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
2021-08-20T13:13:55.8601995Z github.com/urfave/cli/v2.(*App).RunContext(0xc0005d0820, 0x1d2eaa0, 0xc000116030, 0xc0001100d0, 0xd, 0xd, 0x0, 0x0)
2021-08-20T13:13:55.8603131Z 	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
2021-08-20T13:13:55.8603814Z github.com/urfave/cli/v2.(*App).Run(...)
2021-08-20T13:13:55.8604482Z 	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
2021-08-20T13:13:55.8605183Z main.main()
2021-08-20T13:13:55.8605738Z 	/home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x87
```

## Output of run with `-debug`:

```
trivy --debug config  --format  template --template @contrib/sarif.tpl --exit-code 0 --severity  UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --output  trivy-results.sarif ./terraform/environment 
2021-08-20T17:05:03.972-0700    DEBUG   Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2021-08-20T17:05:04.023-0700    DEBUG   cache dir:  /Users/simar/Library/Caches/trivy
2021-08-20T17:05:04.023-0700    DEBUG   Vulnerability type:  []
2021-08-20T17:05:04.077-0700    DEBUG   Analysis error: unable to parse modules/lambda_function/.terraform.lock.hcl: failed to parse modules/lambda_function/.terraform.lock.hcl: unrecognized executable format
WARNING: Failed to load module: missing module with source 'git@github.com:ministryofjustice/terraform-aws-moj-ip-whitelist.git' -  try to 'terraform init' first
2021-08-20T17:05:04.217-0700    DEBUG   OS is not detected and vulnerabilities in OS packages are not detected.
2021-08-20T17:05:04.217-0700    INFO    Detected config files: 35
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: ecs_front.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: resource_group.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: pagerduty.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: ecs_admin.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: credentials.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: ecs_api_cron.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: dynamo_db.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: ecs_pdf.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: load_balancer_admin.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: cloudwatch_logs.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: config_file.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: lambda_functions.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: load_balancer_front.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: modules/ecs_autoscaling/main.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: modules/ecs_autoscaling/variables.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: modules/ecs_scheduled_scaling/main.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: modules/ecs_scheduled_scaling/variables.tf
2021-08-20T17:05:04.217-0700    DEBUG   Scanned config file: modules/lambda_function/iam.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: modules/lambda_function/main.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: modules/lambda_function/variables.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: modules/aurora/variables.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: modules/aurora/main.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: sqs.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: variables.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: autoscaling.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: ecs_seeding.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: ecs_hibernation.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: ecs_api.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: ecs_cluster.tf
2021-08-20T17:05:04.218-0700    DEBUG   Scanned config file: rds.tf
2021-08-20T17:05:04.220-0700    DEBUG   Scanned config file: sns.tf
2021-08-20T17:05:04.220-0700    DEBUG   Scanned config file: locals.tf
2021-08-20T17:05:04.220-0700    DEBUG   Scanned config file: vpc_data.sources.tf
2021-08-20T17:05:04.220-0700    DEBUG   Scanned config file: cloudwatch_alarms.tf
2021-08-20T17:05:04.220-0700    DEBUG   Scanned config file: dns.tf
```

No vulnerabilities observed.

## Output of `trivy -v`:

```
/Users/simar/go/src/github.com/aquasecurity/trivy/trivy -v
Version: v0.19.2-14-g40ed227
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2021-08-20 18:04:17.703944017 +0000 UTC
  NextUpdate: 2021-08-21 00:04:17.703943717 +0000 UTC
  DownloadedAt: 2021-08-20 23:28:01.129212 +0000 UTC
```

## Additional details (base image name, container registry info...):

In this case Trivy was run via Trivy GitHub Action. The action logs are available here: https://github.com/ministryofjustice/opg-lpa/runs/3382241340?check_suite_focus=true#step:4:20

**Comment by simar7** [comment]
Feel free to move this to the tfsec repo if it makes more sense for it to live there.

**Comment by knqyf263** [comment]
Looks the same issue. Don't hesitate to reopen if they are different.
https://github.com/aquasecurity/trivy/issues/1126
