### ISSUE TITLE
Trivy image scan panics with `runtime error: slice bounds out of range [238:237]`

### ISSUE THREAD

**Issue by jkamenik** [aquasecurity/trivy#1842]
## Description

Running Trivy against an image panics with `panic: runtime error: slice bounds out of range [238:237]`

## What did you expect to happen?

It not to panic.

## What happened instead?

It panic-ed.

## Output of run with `-debug`:

```
docker run --rm -it -v /Users/john.kamenik/.trivy/cache:/root/.cache/ -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest --debug image quay.io/mandiant/golang:1.17-20220316120855-john.kamenik
2022-03-16T14:13:42.599Z        DEBUG   Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-03-16T14:13:42.604Z        DEBUG   cache dir:  /root/.cache/trivy
2022-03-16T14:13:42.606Z        DEBUG   DB update was skipped because the local DB is the latest
2022-03-16T14:13:42.607Z        DEBUG   DB Schema: 2, UpdatedAt: 2022-03-16 12:11:15.490216585 +0000 UTC, NextUpdate: 2022-03-16 18:11:15.490216185 +0000 UTC, DownloadedAt: 2022-03-16 13:35:45.877922319 +0000 UTC
2022-03-16T14:13:42.610Z        DEBUG   Vulnerability type:  [os library]
2022-03-16T14:13:42.625Z        DEBUG   Image ID: sha256:a2f7ca9b5a48943340dfa944ce8edfae112a8a3c5f83729afc6335a78a743b07
2022-03-16T14:13:42.625Z        DEBUG   Diff IDs: [sha256:89fda00479fc0fe3bf2c411d92432001870e9dad42ddd0c53715ab77ac4f2a97 sha256:26d5108b2cba762ee9b91c30670091458a0c32b02132620b7f844085af596e22 sha256:48144a6f44ae89c578bd705dba2ebdb2a086b36215affa5659b854308fa22e4b sha256:e3f84a8cee1f3e6a38a463251eb05b87a444dec565a7331217c145e9ef4dd192 sha256:6c14e994de3a023aafde08b658f3d1ca16f9d27666acc9656a1b58acd532301b sha256:7bc74089bb756dd8660afd527ac6ee416e5186db9327bb5f40e400ec2352a448 sha256:687544c6fbca163ac4f3c5673b50610dc40f1110557edc49c0ef1fae119774e4 sha256:4ea3972f8fa5dff80bd5b88fdcf23f1a2d209377dd2cb4bd51982ce1c8ba0563]
2022-03-16T14:13:42.640Z        DEBUG   Missing image ID: sha256:a2f7ca9b5a48943340dfa944ce8edfae112a8a3c5f83729afc6335a78a743b07
2022-03-16T14:13:42.640Z        DEBUG   Missing diff ID: sha256:4ea3972f8fa5dff80bd5b88fdcf23f1a2d209377dd2cb4bd51982ce1c8ba0563
2022-03-16T14:13:42.640Z        DEBUG   Missing diff ID: sha256:7bc74089bb756dd8660afd527ac6ee416e5186db9327bb5f40e400ec2352a448
2022-03-16T14:13:42.640Z        DEBUG   Missing diff ID: sha256:6c14e994de3a023aafde08b658f3d1ca16f9d27666acc9656a1b58acd532301b
2022-03-16T14:14:33.732Z        DEBUG   Analysis error: go binary parse error: read full: EOF
2022-03-16T14:14:33.921Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v0.3.1/_examples/invalid-apples.toml): toml: line 5 (last key "fruit"): Key 'fruit.type' has already been defined.
2022-03-16T14:14:33.923Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v0.3.1/_examples/hard.toml): toml: line 16 (last key "the.hard"): expected '.' or ']' to end table name, but got '#' instead
2022-03-16T14:14:33.924Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/missing-separator.toml): toml: line 1 (last key "wrong"): expected a comma (',') or array terminator (']'), but got '2'
2022-03-16T14:14:33.924Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/no-close-2.toml): toml: line 1 (last key "x"): expected a comma (',') or array terminator (']'), but got end of file
2022-03-16T14:14:33.924Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/no-close-table-2.toml): toml: line 1 (last key "x.key"): newlines not allowed within inline tables
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/no-close-table.toml): toml: line 1 (last key "x.key"): newlines not allowed within inline tables
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/tables-1.toml): toml: line 4: Key 'fruit' was already created and cannot be used as an array.
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/tables-2.toml): toml: line 9 (last key "fruit"): Key 'fruit.variety' has already been defined.
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/no-close.toml): toml: line 1 (last key "long_array"): expected a comma (',') or array terminator (']'), but got end of file
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/text-after-array-entries.toml): toml: line 2 (last key "array"): expected value but found "No" instead
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/text-in-array.toml): toml: line 3 (last key "array"): expected value but found "I" instead
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/array/text-before-array-separator.toml): toml: line 2 (last key "array"): expected a comma (',') or array terminator (']'), but got 'N'
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/bool/mixed-case.toml): toml: line 1 (last key "valid"): expected value but found "False" instead
2022-03-16T14:14:33.925Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/bool/wrong-case-false.toml): toml: line 1 (last key "b"): expected value but found "FALSE" instead
2022-03-16T14:14:33.926Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/bool/wrong-case-true.toml): toml: line 1 (last key "a"): expected value but found "TRUE" instead
2022-03-16T14:14:33.926Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/bare-cr.toml): toml: line 2: TOML files cannot contain control characters: '0x0d'
2022-03-16T14:14:33.926Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/comment-cr.toml): toml: line 1: TOML files cannot contain control characters: '0x0d'
2022-03-16T14:14:33.926Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/comment-del.toml): toml: line 1: TOML files cannot contain control characters: '0x7f'
2022-03-16T14:14:33.926Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/comment-null.toml): toml: line 1: TOML files cannot contain control characters: '0x00'
2022-03-16T14:14:33.926Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/comment-lf.toml): toml: line 1: TOML files cannot contain control characters: '0x10'
2022-03-16T14:14:33.926Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/comment-us.toml): toml: line 1: TOML files cannot contain control characters: '0x1f'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/multi-del.toml): toml: line 1 (last key "multi-del"): TOML files cannot contain control characters: '0x7f'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/multi-null.toml): toml: line 1 (last key "multi-null"): TOML files cannot contain control characters: '0x00'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/multi-lf.toml): toml: line 1 (last key "multi-lf"): TOML files cannot contain control characters: '0x10'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/multi-us.toml): toml: line 1 (last key "multi-us"): TOML files cannot contain control characters: '0x1f'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/rawmulti-del.toml): toml: line 1 (last key "rawmulti-del"): TOML files cannot contain control characters: '0x7f'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/bare-formfeed.toml): toml: line 1 (last key "bare-formfeed"): TOML files cannot contain control characters: '0x0c'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/rawmulti-lf.toml): toml: line 1 (last key "rawmulti-lf"): TOML files cannot contain control characters: '0x10'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/bare-vertical-tab.toml): toml: line 1 (last key "bare-vertical-tab"): TOML files cannot contain control characters: '0x0b'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/rawmulti-null.toml): toml: line 1 (last key "rawmulti-null"): TOML files cannot contain control characters: '0x00'
2022-03-16T14:14:33.927Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/rawmulti-us.toml): toml: line 1 (last key "rawmulti-us"): TOML files cannot contain control characters: '0x1f'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/rawstring-lf.toml): toml: line 1 (last key "rawstring-lf"): TOML files cannot contain control characters: '0x10'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/rawstring-null.toml): toml: line 1 (last key "rawstring-null"): TOML files cannot contain control characters: '0x00'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/rawstring-us.toml): toml: line 1 (last key "rawstring-us"): TOML files cannot contain control characters: '0x1f'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/bare-null.toml): toml: line 1: TOML files cannot contain control characters: '0x00'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/rawstring-del.toml): toml: line 1 (last key "rawstring-del"): TOML files cannot contain control characters: '0x7f'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/string-bs.toml): toml: line 1 (last key "string-bs"): TOML files cannot contain control characters: '0x08'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/string-del.toml): toml: line 1 (last key "string-del"): TOML files cannot contain control characters: '0x7f'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/string-null.toml): toml: line 1 (last key "string-null"): TOML files cannot contain control characters: '0x00'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/string-us.toml): toml: line 1 (last key "string-us"): TOML files cannot contain control characters: '0x1f'
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/hour-over.toml): toml: line 2 (last key "d"): Invalid TOML Datetime: "2006-01-01T24:00:00-00:00".
2022-03-16T14:14:33.928Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/control/string-lf.toml): toml: line 1 (last key "string-lf"): TOML files cannot contain control characters: '0x10'
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/mday-over.toml): toml: line 3 (last key "d"): Invalid TOML Datetime: "2006-01-32T00:00:00-00:00".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/mday-under.toml): toml: line 3 (last key "d"): Invalid TOML Datetime: "2006-01-00T00:00:00-00:00".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/no-leads.toml): toml: line 2 (last key "no-leads"): Invalid TOML Datetime: "1987-7-05T17:45:00Z".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/minute-over.toml): toml: line 2 (last key "d"): Invalid TOML Datetime: "2006-01-01T00:60:00-00:00".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/month-over.toml): toml: line 2 (last key "d"): Invalid TOML Datetime: "2006-13-01T00:00:00-00:00".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/no-leads-with-milli.toml): toml: line 2 (last key "with-milli"): Invalid TOML Datetime: "1987-07-5T17:45:00.12Z".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/month-under.toml): toml: line 2 (last key "d"): Invalid TOML Datetime: "2007-00-01T00:00:00-00:00".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/no-t.toml): toml: line 2 (last key "no-t"): Invalid TOML Datetime: "1987-07-0517:45:00Z".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/second-over.toml): toml: line 3 (last key "d"): Invalid TOML Datetime: "2006-01-01T00:00:61-00:00".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/time-no-leads-2.toml): toml: line 2 (last key "d"): Invalid TOML Datetime: "01:32:0".
2022-03-16T14:14:33.929Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/no-secs.toml): toml: line 2 (last key "no-secs"): Invalid TOML Datetime: "1987-07-05T17:45Z".
2022-03-16T14:14:33.930Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/datetime/trailing-t.toml): toml: line 2 (last key "d"): Invalid TOML Datetime: "2006-01-30T".
2022-03-16T14:14:33.930Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/encoding/bad-utf8-in-comment.toml): toml: line 1: invalid UTF-8 byte: 0xc3
2022-03-16T14:14:33.930Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/encoding/bad-utf8-in-string.toml): toml: line 2 (last key "bad"): invalid UTF-8 byte: 0xc3
2022-03-16T14:14:33.930Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/encoding/bom-not-at-start-1.toml): toml: line 1: invalid UTF-8 byte: 0xff
2022-03-16T14:14:33.930Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/encoding/bom-not-at-start-2.toml): toml: line 1 (last key "bom-not-at-start"): invalid UTF-8 byte: 0xff
2022-03-16T14:14:33.930Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/encoding/utf16-bom.toml): toml: line 1: files cannot contain NULL bytes; probably using UTF-16; TOML files must be UTF-8
2022-03-16T14:14:33.930Z        DEBUG   Analysis error: unable to decode TOML (go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/internal/toml-test/tests/invalid/encoding/utf16.toml): toml: line 1: files cannot contain NULL bytes; probably using UTF-16; TOML files must be UTF-8
panic: runtime error: slice bounds out of range [238:237] [recovered]
        panic: runtime error: slice bounds out of range [238:237]

goroutine 193 [running]:
github.com/BurntSushi/toml.parse.func1()
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/parse.go:33 +0x1b1
panic({0x1bed480, 0xc000c06120})
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1038 +0x215
github.com/BurntSushi/toml.(*lexer).current(...)
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/lex.go:115
github.com/BurntSushi/toml.(*lexer).emit(...)
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/lex.go:131
github.com/BurntSushi/toml.lexMultilineString(0xc000856980)
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/lex.go:725 +0x565
github.com/BurntSushi/toml.(*lexer).nextItem(0xc000856980)
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/lex.go:84 +0xa8
github.com/BurntSushi/toml.(*parser).next(0xc000856a00)
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/parse.go:96 +0x6c
github.com/BurntSushi/toml.(*parser).topLevel(0xc000856a00, {0x12, {0xc000c00800, 0x0}, {0x0, 0x0}, {0x5, 0xe7, 0x1}})
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/parse.go:184 +0x813
github.com/BurntSushi/toml.parse({0xc000c00800, 0xf2})
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/parse.go:71 +0x4c8
github.com/BurntSushi/toml.(*Decoder).Decode(0xc000866e18, {0x19c6960, 0xc000814880})
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.0.0/decode.go:146 +0x68a
github.com/aquasecurity/fanal/analyzer/config/toml.ConfigAnalyzer.Analyze({0x0}, {0x0, 0x2}, {{0x0, 0x0}, {0xc001154690, 0x6d}, {0x2181088, 0xc0011396c0}, {0x7fd006940008, ...}, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220309115321-0183e4870f89/analyzer/config/toml/toml.go:32 +0x70
github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile.func1({0x2173d68, 0x0}, {0x2173dd8, 0xc000d006b0})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220309115321-0183e4870f89/analyzer/analyzer.go:253 +0x275
created by github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220309115321-0183e4870f89/analyzer/analyzer.go:248 +0x3d2
```

## Output of `trivy -v`:

```
docker run --rm -it -v /Users/john.kamenik/.trivy/cache:/root/.cache/ -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest -v
Version: 0.24.3
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-03-16 12:11:15.490216585 +0000 UTC
  NextUpdate: 2022-03-16 18:11:15.490216185 +0000 UTC
  DownloadedAt: 2022-03-16 13:35:45.877922319 +0000 UTC
```

## Additional details (base image name, container registry info...):

From the output it might be due to an invalid DB.

I have the same failure using the [trivy-action](https://github.com/aquasecurity/trivy-action) in GitHub Actions.

**Comment by knqyf263** [comment]
@afdesk Seems like the error is from BurntSushi/toml. Can you please take a look?

**Comment by afdesk** [comment]
@jkamenik thanks for your report! 
I'll take a look at this issue

**Comment by jkamenik** [comment]
Any update or at least suggestion on fix?  Right now we have disabled Trivy in our CI/CD which is less then idea.

**Comment by afdesk** [comment]
@jkamenik oh, give me some time. I'm going to investigate it today.

**Comment by afdesk** [comment]
@jkamenik sorry for waiting, I forgot that it's a known issue in [BurntSushi/toml](https://github.com/BurntSushi/toml).
duplicate #1372 

I asked to fix it, but it isn't important...
https://github.com/BurntSushi/toml/issues/329
https://github.com/BurntSushi/toml/pull/330#issuecomment-970369632

so, there is a solution (https://github.com/aquasecurity/trivy/issues/1372#issuecomment-970404519) to skip folder `go/pkg`:
```sh
$ trivy i --skip-dirs go/pkg demo:test
```
I hope it will help you.

**Comment by arp242** [comment]
Should be fixed if you update your dependency to github.com/BurntSushi/toml@v1.1.0, which I just released.

**Comment by afdesk** [comment]
@arp242 thanks a lot for your effort! I'll update it
