### ISSUE TITLE
panic: interface conversion: interface {} is map[string]*parser.Property, not string

### ISSUE THREAD

**Issue by PenelopeFudd** [aquasecurity/trivy#1892]
## Description

```
$ grep DESC /etc/lsb-release
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
$ /usr/local/bin/trivy rootfs  /

panic: interface conversion: interface {} is map[string]*parser.Property, not string

goroutine 1 [running]:
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Property).AsString(0xc019a51b80)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/property_helpers.go:105 +0xa9
github.com/aquasecurity/defsec/parsers/cloudformation/parser.ResolveBase64(0xc019a51b00)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/fn_base64.go:14 +0x66
github.com/aquasecurity/defsec/parsers/cloudformation/parser.ResolveIntrinsicFunc(0xc019a51b00)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/intrinsics.go:72 +0x114
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Property).resolveValue(0xc00a56ad00)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/property.go:151 +0x2e
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Property).IsList(0xc019a51b00)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/property_helpers.go:67 +0x3a
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Property).setContext(0xc019a51b00, 0xc001537620)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/property.go:63 +0xcc
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Resource).setContext(0xc004615360, 0xc001537620)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/resource.go:51 +0xbb
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Resource).ConfigureResource(0xc00313f370, {0xc0197ca300, 0x1000}, {0xc00017cc00, 0x2b}, 0x4601e6)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/resource.go:27 +0x55
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Parser).Parse(0xc01fd0c030, {0x2142e60, 0xc01377ed20}, {0xc00017cc00, 0xc00017cc00})
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/parser.go:128 +0x596
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Parser).ParseFiles.func1(0xc00017cc00, {0xc00017cc00, 0x2b}, 0xc00313f4e8, 0xc00313f500)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/parser.go:62 +0x147
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Parser).ParseFiles(0x0, {0xc00a354000, 0x13f, 0x0})
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/parsers/cloudformation/parser/parser.go:69 +0x115
github.com/aquasecurity/defsec/scanners/cloudformation/scanner.(*Scanner).Scan(0xc00011a050)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/scanners/cloudformation/scanner/scanner.go:86 +0x5e
github.com/aquasecurity/fanal/config/scanner.Scanner.scanCloudFormation({{0x7ffe6d308652, 0x1}, {0x0, 0x0, 0x0}, 0x0, 0xc000a3a000, 0xc00011a050}, {0xc01c2c2000, 0x13f, ...})
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220317181013-c4fac2e5fe9c/config/scanner/scanner.go:151 +0x297
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs({{0x7ffe6d308652, 0x1}, {0x0, 0x0, 0x0}, 0x0, 0xc000a3a000, 0xc00011a050}, {0x2171e98, 0xc000a158c0}, ...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220317181013-c4fac2e5fe9c/config/scanner/scanner.go:97 +0x465
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect({{0x7ffe6d308652, 0x1}, {0x7f2b4e948a18, 0xc0008bae00}, {{{0x0, 0x0, 0x0}, {0xc000a40000, 0x3, 0x4}}}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220317181013-c4fac2e5fe9c/artifact/local/fs.go:115 +0x345
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0xc000b30560, 0x2, 0x2}, {0xc0008bad50, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/scanner/scan.go:94 +0xce
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{0xc000b2e9c0, 0xc00000e708, {0x2117190, 0x6}, 0x0, 0x0, {0xc0001b7980, 0x1f}}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:217 +0x8fe
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout({_, _}, {{0xc000b2e9c0, 0xc00000e708, {0x2117190, 0x6}, 0x0, 0x0, {0xc0001b7980, 0x1f}}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:68 +0x44c
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{0xc000b2e9c0, 0xc00000e708, {0x2117190, 0x6}, 0x0, 0x0, {0xc0001b7980, 0x1f}}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:40 +0xca
github.com/aquasecurity/trivy/pkg/commands/artifact.RootfsRun(0xc000b2e9c0)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/fs.go:48 +0x1a6
github.com/urfave/cli/v2.(*Command).Run(0xc000b10360, 0xc000b2e0c0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc000391380, {0x2171e60, 0xc0001aa020}, {0xc00018e060, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x4f

```

## What did you expect to happen?
It should have worked.

## What happened instead?
It died with a big error message.

## Output of run with `-debug`:

 
[debug.txt](https://github.com/aquasecurity/trivy/files/8377303/debug.txt)
 

## Output of `trivy -v`:

```
Version: 0.24.4
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-03-30 00:09:48.580946703 +0000 UTC
  NextUpdate: 2022-03-30 06:09:48.580946503 +0000 UTC
  DownloadedAt: 2022-03-30 05:18:22.996974423 +0000 UTC
```

## Additional details (base image name, container registry info...):
Trivy is working on most of our machines, it's just dying on a few, like this one.

**Comment by PenelopeFudd** [comment]
From the debug log, the last filename it printed was: https://github.com/hashicorp/hcl/blob/v1.0.0/test-fixtures/multiline_literal.hcl
The line that died: https://github.com/aquasecurity/defsec/blob/v0.17.1/parsers/cloudformation/parser/property_helpers.go#L105

**Comment by PenelopeFudd** [comment]
After a bit more work, it looks like this file is the culprit: /etc/heat/templates/AWS_RDS_DBInstance.yaml , from this package: 
```
Package: heat-common
Version: 1:16.0.0-0ubuntu1~cloud0
Priority: optional
Section: web
Source: heat
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: PKG OpenStack <openstack-devel@lists.alioth.debian.org>
Installed-Size: 82.9 kB
Depends: adduser
Supported: 48m
Download-Size: 25.3 kB
APT-Manual-Installed: no
APT-Sources: http://ubuntu-cloud.archive.canonical.com/ubuntu focal-updates/wallaby/main amd64 Packages
Description: OpenStack orchestration service - common files
 Heat is a service to orchestrate multiple composite cloud applications using
 templates, through both an OpenStack-native ReST API and a
 CloudFormation-compatible Query API.
 .
 This package contains the common files.
```

File: [AWS_RDS_DBInstance.yaml.txt](https://github.com/aquasecurity/trivy/files/8377659/AWS_RDS_DBInstance.yaml.txt)
The .txt extension was added to allow attaching it to this ticket.
