### ISSUE TITLE
trivy crash (cfsec issue)

### ISSUE THREAD

**Issue by apeyrat** [aquasecurity/trivy#1906]
## Description
Running the following command makes trivy crash:

trivy fs cf-test.yaml

(I found the issue while using cfsec but logging it in trivy as it seems now embedded)

I'm running it on debian11 in WSL2

Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xf2360b]

goroutine 1 [running]:
github.com/aquasecurity/defsec/rules/aws/apigateway.glob..func1(0xc0007b1800)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/rules/aws/apigateway/enable_access_logging.go:43 +0x1ab
github.com/aquasecurity/defsec/rules.RegisteredRule.Evaluate({{{0x1cd4257, 0xc}, {0x1cf07b4, 0x15}, {0x1d680c9, 0x43}, {0x1d87577, 0xa7}, {0x1d5ecbd, 0x39}, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/rules/register.go:24 +0x2a
github.com/aquasecurity/defsec/scanners/cloudformation/scanner.(*Scanner).Scan(0xc000542320)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/scanners/cloudformation/scanner/scanner.go:101 +0x3c5
github.com/aquasecurity/fanal/config/scanner.Scanner.scanCloudFormation({{0x7ffd8b71437e, 0x1b}, {0x0, 0x0, 0x0}, 0x0, 0xc0008ff570, 0xc000542320}, {0xc0008f9cb0, 0x1, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/config/scanner/scanner.go:151 +0x296
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs({{0x7ffd8b71437e, 0x1b}, {0x0, 0x0, 0x0}, 0x0, 0xc0008ff570, 0xc000542320}, {0x218d638, 0xc0007111a0}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/config/scanner/scanner.go:97 +0x465
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect({{0x7ffd8b71437e, 0x1b}, {0x7f8f50c48cf8, 0xc00047aae0}, {{{0x0, 0x0, 0x0}, {0xc0008e5480, 0x3, 0x4}}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/artifact/local/fs.go:115 +0x345
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0xc00093e5c0, 0x2, 0x2}, {0xc00047a5b0, ...}, ...})
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:109 +0x103
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{0xc0008e52c0, 0xc00000ec50, {0x2177354, 0x6}, 0x0, 0x0, {0xc000118a38, 0x18}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:257 +0xafe
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout({_, _}, {{0xc0008e52c0, 0xc00000ec50, {0x2177354, 0x6}, 0x0, 0x0, {0xc000118a38, 0x18}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:92 +0x48c
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{0xc0008e52c0, 0xc00000ec50, {0x2177354, 0x6}, 0x0, 0x0, {0xc000118a38, 0x18}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:60 +0xca
github.com/aquasecurity/trivy/pkg/commands/artifact.FilesystemRun(0xc0008e52c0)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/fs.go:49 +0x20f
github.com/urfave/cli/v2.(*Command).Run(0xc0007ad7a0, 0xc0008e48c0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc000683d40, {0x218d600?, 0xc00003e0f0}, {0xc00003a090, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x4f
```

## Content of cf-test.yaml
```
---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref AWS::StackName
      ProtocolType: HTTP

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      AutoDeploy: true
      StageName: "$default"
```

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
❯ trivy -v
Version: 0.25.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-03-31 12:11:44.661302354 +0000 UTC
  NextUpdate: 2022-03-31 18:11:44.661301954 +0000 UTC
  DownloadedAt: 2022-03-31 12:44:08.451449364 +0000 UTC                                                                                                 /0.0s
```

**Comment by isuftin** [comment]
Same:

```sh
trivy config cloudformation/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1b34c3b]

goroutine 1 [running]:
github.com/aquasecurity/defsec/rules/aws/eks.glob..func1(0xc0001df000)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/rules/aws/eks/enable_control_plane_logging.go:33 +0xfb
github.com/aquasecurity/defsec/rules.RegisteredRule.Evaluate({{{0x28dcb93, 0xc}, {0x2914618, 0x1c}, {0x296e14f, 0x40}, {0x2994e0d, 0xca}, {0x296a5ba, 0x3c}, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/rules/register.go:24 +0x2a
github.com/aquasecurity/defsec/scanners/cloudformation/scanner.(*Scanner).Scan(0xc00053abe0)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.17.1/scanners/cloudformation/scanner/scanner.go:101 +0x3c5
github.com/aquasecurity/fanal/config/scanner.Scanner.scanCloudFormation({{0x7ffeefbfd395, 0xf}, {0xc000a67380, 0x2, 0x2}, 0xc001026600, 0xc000a55b90, 0xc00053abe0}, {0xc000626600, 0x5, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/config/scanner/scanner.go:151 +0x296
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs({{0x7ffeefbfd395, 0xf}, {0xc000a67380, 0x2, 0x2}, 0xc001026600, 0xc000a55b90, 0xc00053abe0}, {0x2d952b8, 0xc0008afaa0}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/config/scanner/scanner.go:97 +0x465
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect({{0x7ffeefbfd395, 0xe}, {0xd142258, 0xc00042ca40}, {{{0x0, 0x0, 0x0}, {0xc001026640, 0x3, 0x4}}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220324154234-b2df5b98f8cd/artifact/local/fs.go:115 +0x345
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0x0, 0x0, 0x0}, {0xc00042c5a0, ...}, ...})
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:109 +0x103
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{0xc000599c00, 0xc00000ea58, {0x2d7ed84, 0x6}, 0x0, 0x0, {0xc000a15620, 0x23}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:257 +0xafe
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout({_, _}, {{0xc000599c00, 0xc00000ea58, {0x2d7ed84, 0x6}, 0x0, 0x0, {0xc000a15620, 0x23}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:92 +0x48c
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{0xc000599c00, 0xc00000ea58, {0x2d7ed84, 0x6}, 0x0, 0x0, {0xc000a15620, 0x23}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:60 +0xca
github.com/aquasecurity/trivy/pkg/commands/artifact.ConfigRun(0xc000599c00)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/config.go:29 +0x2af
github.com/urfave/cli/v2.(*Command).Run(0xc000ac25a0, 0xc0005994c0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc000682b60, {0x2d95280?, 0xc000048150}, {0xc00003a0c0, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x4f

trivy --version
Version: 0.25.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-03-31 18:05:56.172690541 +0000 UTC
  NextUpdate: 2022-04-01 00:05:56.172689841 +0000 UTC
  DownloadedAt: 2022-03-31 19:08:04.997936 +0000 UTC
```
