### ISSUE TITLE
Out of memory: Kill process 3991 (trivy) -- version 0.27.0

### ISSUE THREAD

**Issue by PenelopeFudd** [aquasecurity/trivy#2017]
## Description

Trivy uses up all available memory and is terminated by the Linux OOM killer.

Is there a way to tell Trivy to trade memory for speed?

## What did you expect to happen?

It should "just work".

## What happened instead?

Trivy was killed while running, because memory ran out.

## Output of run with `-debug`:

n/a

## Output of `trivy -v`:

Version: 0.27.0

## Additional details (base image name, container registry info...):

```
Apr 20 03:49:00 webserver kernel: [6161242.298041] Mem-Info:
Apr 20 03:49:00 webserver kernel: [6161242.298047] active_anon:3562980 inactive_anon:323930 isolated_anon:0
Apr 20 03:49:00 webserver kernel: [6161242.298047]  active_file:2113 inactive_file:1952 isolated_file:128
Apr 20 03:49:00 webserver kernel: [6161242.298047]  unevictable:4210 dirty:0 writeback:0 unstable:0
Apr 20 03:49:00 webserver kernel: [6161242.298047]  slab_reclaimable:32856 slab_unreclaimable:20649
Apr 20 03:49:00 webserver kernel: [6161242.298047]  mapped:25240 shmem:806592 pagetables:94948 bounce:0
Apr 20 03:49:00 webserver kernel: [6161242.298047]  free:34882 free_pcp:0 free_cma:0
Apr 20 03:49:00 webserver kernel: [6161242.298050] Node 0 active_anon:14251920kB inactive_anon:1295720kB active_file:8452kB inactive_file:7808kB unevictable:16840kB isolated(anon):0kB isolated(file):512kB mapped:100960kB dirty:0kB writeback:0kB shmem:3226368kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
Apr 20 03:49:00 webserver kernel: [6161242.298051] Node 0 DMA free:15908kB min:64kB low:80kB high:96kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Apr 20 03:49:00 webserver kernel: [6161242.298054] lowmem_reserve[]: 0 1926 15976 15976 15976
Apr 20 03:49:00 webserver kernel: [6161242.298055] Node 0 DMA32 free:64256kB min:8140kB low:10172kB high:12204kB active_anon:1589284kB inactive_anon:263388kB active_file:228kB inactive_file:236kB unevictable:0kB writepending:0kB present:2080596kB managed:2015028kB mlocked:0kB kernel_stack:1724kB pagetables:37004kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Apr 20 03:49:00 webserver kernel: [6161242.298058] lowmem_reserve[]: 0 0 14049 14049 14049
Apr 20 03:49:00 webserver kernel: [6161242.298060] Node 0 Normal free:59364kB min:59372kB low:74212kB high:89052kB active_anon:12662636kB inactive_anon:1032332kB active_file:9128kB inactive_file:7760kB unevictable:16840kB writepending:0kB present:14680064kB managed:14393364kB mlocked:16840kB kernel_stack:15028kB pagetables:342788kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Apr 20 03:49:00 webserver kernel: [6161242.298062] lowmem_reserve[]: 0 0 0 0 0
Apr 20 03:49:00 webserver kernel: [6161242.298064] Node 0 DMA: 1*4kB (U) 0*8kB 0*16kB 1*32kB (U) 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15908kB
Apr 20 03:49:00 webserver kernel: [6161242.298070] Node 0 DMA32: 860*4kB (UME) 904*8kB (UME) 819*16kB (UME) 583*32kB (UME) 245*64kB (UME) 50*128kB (UME) 1*256kB (E) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 64768kB
Apr 20 03:49:00 webserver kernel: [6161242.298075] Node 0 Normal: 729*4kB (UME) 2253*8kB (UME) 1679*16kB (UME) 395*32kB (M) 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 60444kB
Apr 20 03:49:00 webserver kernel: [6161242.298081] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
Apr 20 03:49:00 webserver kernel: [6161242.298083] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Apr 20 03:49:00 webserver kernel: [6161242.298083] 812110 total pagecache pages
Apr 20 03:49:00 webserver kernel: [6161242.298086] 123 pages in swap cache
Apr 20 03:49:00 webserver kernel: [6161242.298087] Swap cache stats: add 26799996, delete 26800831, find 416548370/421320087
Apr 20 03:49:00 webserver kernel: [6161242.298087] Free swap  = 0kB
Apr 20 03:49:00 webserver kernel: [6161242.298088] Total swap = 4190204kB
Apr 20 03:49:00 webserver kernel: [6161242.298089] 4194163 pages RAM
Apr 20 03:49:00 webserver kernel: [6161242.298089] 0 pages HighMem/MovableOnly
Apr 20 03:49:00 webserver kernel: [6161242.298089] 88088 pages reserved
Apr 20 03:49:00 webserver kernel: [6161242.298090] 0 pages cma reserved
Apr 20 03:49:00 webserver kernel: [6161242.298090] 0 pages hwpoisoned
Apr 20 03:49:00 webserver kernel: [6161242.298091] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
...
Apr 20 03:49:00 webserver kernel: [6161242.300895] [32286]  1000 32286    82438    22240   573440      141             0 python3
Apr 20 03:49:00 webserver kernel: [6161242.300896] [32411]   115 32411  1132722     5295  5771264      368             0 postgres
Apr 20 03:49:00 webserver kernel: [6161242.300898] [ 3991]     0  3991  1538364  1154121 10031104    69455             0 trivy
Apr 20 03:49:00 webserver kernel: [6161242.300902] [ 5899]     0  5899    50666      781   421888        6             0 sssd_nss
Apr 20 03:49:00 webserver kernel: [6161242.300904] [ 5947]   114  5947  7657418  1155086 24174592     5058             0 java
Apr 20 03:49:00 webserver kernel: [6161242.300905] [ 6158]   114  6158    30240      490   110592        0             0 controller
Apr 20 03:49:00 webserver kernel: [6161242.300908] [ 6359]   113  6359     2071      285    61440        0             0 erlexec
Apr 20 03:49:00 webserver kernel: [6161242.300909] [ 6361]   115  6361  1129686      445   303104      376             0 postgres
Apr 20 03:49:00 webserver kernel: [6161242.300911] [ 6363]   113  6363     1159      165    53248        0             0 sh
Apr 20 03:49:00 webserver kernel: [6161242.300912] [ 6365]   115  6365  1129953     1026   368640      391             0 postgres
Apr 20 03:49:00 webserver kernel: [6161242.300913] Out of memory: Kill process 3991 (trivy) score 230 or sacrifice child 
Apr 20 03:49:00 webserver kernel: [6161242.322144] Killed process 3991 (trivy) total-vm:6153456kB, anon-rss:4616484kB, file-rss:0kB, shmem-rss:0kB
Apr 20 03:49:00 webserver kernel: [6161242.823472] oom_reaper: reaped process 3991 (trivy), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by DmitriyLewen** [comment]
Hello @PenelopeFudd 
Thanks for your report.

Trivy doesn't have ability to limit memory.
To reproduce your issue, could you please provide more information: what are you scanning, computer resources, etc.

Regards, Dmitriy

**Comment by PenelopeFudd** [comment]
I've got a script that runs this as root: 
```
ulimit -n 102400  # to address trivy running out of file descriptors
/usr/local/bin/trivy rootfs --timeout 60m -s CRITICAL,HIGH --skip-dirs /cache --skip-dirs /repo --skip-dirs /tmp/package-staging -f json -o trivy-scan.json.now / 
```
This server has 64GB of ram:
```
# free -g 
              total        used        free      shared  buff/cache   available
Mem:             62          32          28           0           1          29
Swap:             7           7           0
```
The system has about 1 TB of data, but most of that is used by 5 virtual machines.

Here's the memory usage of my server from when trivy started until it was killed:
![History  refreshed every 30 sec](https://user-images.githubusercontent.com/1606480/165374318-7bbe7f1e-5fb3-4bc2-a888-92eebdc80326.png)

Essentially, it looks like trivy used up 23GB of RAM and was killed after running for 35 minutes.

Note: I've tried this on several other servers, and trivy is being killed by the OOM killer on most of them.

Note^2: I just downloaded the latest version (0.27.0) today and these OOM events are from that; it's even worse than 0.26.0.

**Comment by PenelopeFudd** [comment]
Here's the stderr of the process, with newlines inserted: 
```
2022-04-26T11:23:02.049-0700	INFO	Need to update DB
2022-04-26T11:23:02.049-0700	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2022-04-26T11:23:02.049-0700	INFO	Downloading DB...
22.03 MiB / 31.59 MiB [------------------------------------------>__________________] 69.74%  p/s 
31.59 MiB / 31.59 MiB [----------------------------------------------------------->] 100.00% ? p/s 
31.59 MiB / 31.59 MiB [----------------------------------------------------------->] 100.00% ? p/s 
31.59 MiB / 31.59 MiB [---------------------------------------------->] 100.00% 15.93 MiB p/s ETA 0s
31.59 MiB / 31.59 MiB [---------------------------------------------->] 100.00% 15.93 MiB p/s ETA 0s
31.59 MiB / 31.59 MiB [---------------------------------------------->] 100.00% 15.93 MiB p/s ETA 0s
31.59 MiB / 31.59 MiB [---------------------------------------------->] 100.00% 14.90 MiB p/s ETA 0s
31.59 MiB / 31.59 MiB [---------------------------------------------->] 100.00% 14.90 MiB p/s ETA 0s
31.59 MiB / 31.59 MiB [---------------------------------------------->] 100.00% 14.90 MiB p/s ETA 0s
31.59 MiB / 31.59 MiB [---------------------------------------------->] 100.00% 13.94 MiB p/s ETA 0s
31.59 MiB / 31.59 MiB [-------------------------------------------------] 100.00% 17.28 MiB p/s 2.0s
Killed
```

**Comment by PenelopeFudd** [comment]
With a limit on memory usage, it dies after a minute or two:
```
# ulimit -v 10000000 
# /usr/local/bin/trivy rootfs --timeout 60m -s CRITICAL,HIGH --skip-dirs /cache --skip-dirs /repo --skip-dirs /tmp/package-staging -f json -o trivy-scan.json.now /

##### lots of copies of this:
goroutine 5077 [select]:
golang.org/x/sync/semaphore.(*Weighted).Acquire(0xc00074c500, {0x2244bb0, 0xc0011e0ae0}, 0x1)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/semaphore/semaphore.go:60 +0x345
github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile({{0xc000d81000, 0x23, 0x40}, {0x0, 0x0, 0x0}}, {0x2244bb0?, 0xc0011e0ae0}, 0xc0008a3ac0, 0xc00074c500, ...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220425071928-af75d05f1e6e/analyzer/analyzer.go:274 +0x245
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect.func1({0xc17fa7ec80?, 0xc17fa7ec80?}, {0x2249bb8, 0xc182708340}, 0x4e?)
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220425071928-af75d05f1e6e/artifact/local/fs.go:104 +0x2b4
github.com/aquasecurity/fanal/walker.FS.Walk.func1({0xc17fa7ebe0?, 0xc1578262c0?}, {0x2249bb8, 0xc182708340})
	/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220425071928-af75d05f1e6e/walker/fs.go:41 +0x127
github.com/saracen/walker.(*walker).walk(0xc00077c6c0, {0xc1578262c0, 0x3f}, {0x2249bb8, 0xc182708340})
	/home/runner/go/pkg/mod/github.com/saracen/walker@v0.0.0-20191201085201-324a081bae7e/walker.go:76 +0x8d
github.com/saracen/walker.(*walker).readdir(0xc00077c6c0?, {0xc1578262c0, 0x3f})
	/home/runner/go/pkg/mod/github.com/saracen/walker@v0.0.0-20191201085201-324a081bae7e/walker_unix.go:46 +0x3c7
github.com/saracen/walker.(*walker).walk(0xc00077c6c0, {0xc14f398180, 0x39}, {0x2249bb8, 0xc15787a000})
	/home/runner/go/pkg/mod/github.com/saracen/walker@v0.0.0-20191201085201-324a081bae7e/walker.go:110 +0x1e8
github.com/saracen/walker.(*walker).readdir(0xc00077c6c0?, {0xc14f398180, 0x39})
	/home/runner/go/pkg/mod/github.com/saracen/walker@v0.0.0-20191201085201-324a081bae7e/walker_unix.go:46 +0x3c7
github.com/saracen/walker.(*walker).gowalk(0xc00077c6c0, {0xc14f398180, 0x39})
	/home/runner/go/pkg/mod/github.com/saracen/walker@v0.0.0-20191201085201-324a081bae7e/walker.go:118 +0x28
github.com/saracen/walker.(*walker).walk.func1()
	/home/runner/go/pkg/mod/github.com/saracen/walker@v0.0.0-20191201085201-324a081bae7e/walker.go:103 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

```

In another window, I was running 'pstree' repeatedly, and saw this:
```
        │      ├─sshd───sshd───bash───sudo───bash───trivy───56*[{trivy}]
```
It looks like trivy is spawning lots of sub-processes (or threads), and ends up running out of resources (e.g. memory).

**Comment by DmitriyLewen** [comment]
Hello @PenelopeFudd 
We fix your issue in next release.
At the moment, you can use `--security-checks vuln` flag.

Regards, Dmitriy

**Comment by PenelopeFudd** [comment]
Ok, thanks; do you know when the next release will come out, approximately?  If it's a couple of days or a couple of weeks?  Thanks

**Comment by DmitriyLewen** [comment]
These changes are already available for Trivy v0.27.1.
Currently you can [install](https://aquasecurity.github.io/trivy/v0.27.1/getting-started/installation/) it.

**Comment by knqyf263** [comment]
You can track the next version here.
https://github.com/aquasecurity/trivy/milestone/5

**Comment by PenelopeFudd** [comment]
I just tried version 0.30.4, and still ran out of memory.  :-( 

```
ulimit -n 102400
 cd /tmp
 /usr/local/bin/trivy rootfs --timeout 60m -s CRITICAL,HIGH --skip-dirs /cache  \
    -f json -o trivy-scan.json.new / > trivy-scan.stderr 2>&1 \
&& mv trivy-scan.json.new trivy-scan.json
```
Dmesg -T output: 
```
[Wed Aug  3 22:26:58 2022] node invoked oom-killer: gfp_mask=0x14200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
[Wed Aug  3 22:26:58 2022] node cpuset=/ mems_allowed=0
[Wed Aug  3 22:26:58 2022] CPU: 5 PID: 7604 Comm: node Not tainted 4.15.0-175-generic #184-Ubuntu
[Wed Aug  3 22:26:58 2022] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-1ubuntu1.1 04/01/2014
[Wed Aug  3 22:26:58 2022] Mem-Info:
[Wed Aug  3 22:26:58 2022] active_anon:3130320 inactive_anon:784141 isolated_anon:0
                            active_file:2131 inactive_file:1999 isolated_file:126
                            unevictable:4011 dirty:0 writeback:0 unstable:0
                            slab_reclaimable:42286 slab_unreclaimable:44735
                            mapped:271793 shmem:271078 pagetables:38029 bounce:0
                            free:33760 free_pcp:0 free_cma:0
[Wed Aug  3 22:26:58 2022] Node 0 active_anon:12521280kB inactive_anon:3136564kB active_file:8524kB inactive_file:7996kB unevictable:16044kB isolated(anon):0kB isolated(file):504kB mapped:1087172kB dirty:0kB writeback:0kB shmem:1084312kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 1421312kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[Wed Aug  3 22:26:58 2022] Node 0 DMA free:15908kB min:64kB low:80kB high:96kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[Wed Aug  3 22:26:58 2022] lowmem_reserve[]: 0 2949 15975 15975 15975
[Wed Aug  3 22:26:58 2022] Node 0 DMA32 free:64208kB min:12464kB low:15580kB high:18696kB active_anon:2450592kB inactive_anon:427772kB active_file:0kB inactive_file:320kB unevictable:808kB writepending:0kB present:3129172kB managed:3063604kB mlocked:808kB kernel_stack:1824kB pagetables:19604kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[Wed Aug  3 22:26:58 2022] lowmem_reserve[]: 0 0 13025 13025 13025
[Wed Aug  3 22:26:58 2022] Node 0 Normal free:54924kB min:55048kB low:68808kB high:82568kB active_anon:10070688kB inactive_anon:2708792kB active_file:9088kB inactive_file:6776kB unevictable:15236kB writepending:0kB present:13631488kB managed:13344572kB mlocked:15236kB kernel_stack:13792kB pagetables:132512kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[Wed Aug  3 22:26:58 2022] lowmem_reserve[]: 0 0 0 0 0
[Wed Aug  3 22:26:58 2022] Node 0 DMA: 1*4kB (U) 0*8kB 0*16kB 1*32kB (U) 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15908kB
[Wed Aug  3 22:26:58 2022] Node 0 DMA32: 1902*4kB (UME) 1377*8kB (UME) 951*16kB (UME) 554*32kB (UME) 163*64kB (UME) 24*128kB (UME) 2*256kB (M) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 65584kB
[Wed Aug  3 22:26:58 2022] Node 0 Normal: 768*4kB (UME) 2564*8kB (UME) 1433*16kB (UME) 304*32kB (UME) 1*64kB (M) 1*128kB (M) 1*256kB (M) 0*512kB 1*1024kB (M) 0*2048kB 0*4096kB = 57712kB
[Wed Aug  3 22:26:58 2022] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[Wed Aug  3 22:26:58 2022] 336390 total pagecache pages
[Wed Aug  3 22:26:58 2022] 59781 pages in swap cache
[Wed Aug  3 22:26:58 2022] Swap cache stats: add 1452525, delete 1392795, find 53772452/53971407
[Wed Aug  3 22:26:58 2022] Free swap  = 0kB
[Wed Aug  3 22:26:58 2022] Total swap = 998396kB
[Wed Aug  3 22:26:58 2022] 4194163 pages RAM
[Wed Aug  3 22:26:58 2022] 0 pages HighMem/MovableOnly
[Wed Aug  3 22:26:58 2022] 88142 pages reserved
[Wed Aug  3 22:26:58 2022] 0 pages cma reserved
[Wed Aug  3 22:26:58 2022] 0 pages hwpoisoned
[Wed Aug  3 22:26:58 2022] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name

...
[Wed Aug  3 22:26:58 2022] Out of memory: Kill process 15663 (trivy) score 365 or sacrifice child
[Wed Aug  3 22:26:58 2022] Killed process 15663 (trivy) total-vm:8644228kB, anon-rss:6551344kB, file-rss:0kB, shmem-rss:0kB
[Wed Aug  3 22:26:58 2022] oom_reaper: reaped process 15663 (trivy), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by PenelopeFudd** [comment]
Stdout+stderr output:
```
2022-08-03T22:25:02.782-0700	INFO	Need to update DB
2022-08-03T22:25:02.782-0700	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2022-08-03T22:25:02.782-0700	INFO	Downloading DB...
12.33 MiB / 33.48 MiB [---------------------->______________________________________] 36.82% ? p/s ?23.55 MiB / 33.48 MiB [------------------------------------------>__________________] 70.32% ? p/s ?33.48 MiB / 33.48 MiB [----------------------------------------------------------->] 100.00% ? p/s ?33.48 MiB / 33.48 MiB [---------------------------------------------->] 100.00% 35.27 MiB p/s ETA 0s33.48 MiB / 33.48 MiB [---------------------------------------------->] 100.00% 35.27 MiB p/s ETA 0s33.48 MiB / 33.48 MiB [---------------------------------------------->] 100.00% 35.27 MiB p/s ETA 0s33.48 MiB / 33.48 MiB [---------------------------------------------->] 100.00% 32.99 MiB p/s ETA 0s33.48 MiB / 33.48 MiB [---------------------------------------------->] 100.00% 32.99 MiB p/s ETA 0s33.48 MiB / 33.48 MiB [---------------------------------------------->] 100.00% 32.99 MiB p/s ETA 0s33.48 MiB / 33.48 MiB [---------------------------------------------->] 100.00% 30.86 MiB p/s ETA 0s33.48 MiB / 33.48 MiB [-------------------------------------------------] 100.00% 17.19 MiB p/s 2.1s2022-08-03T22:25:05.876-0700	INFO	Vulnerability scanning is enabled
2022-08-03T22:25:05.876-0700	INFO	Secret scanning is enabled
2022-08-03T22:25:05.876-0700	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-08-03T22:25:05.876-0700	INFO	Please see also https://aquasecurity.github.io/trivy/0.30.4/docs/secret/scanning/#recommendation for faster secret detection
Killed

```

**Comment by PenelopeFudd** [comment]
When `--security-checks vuln` was added, the scan ran to completion.  Some points:
* Yayyy, it wasn't killed!
* The message should probably say "if your scan runs out of memory and is killed" instead of "if your scanning is slow".
* How should users scan for secrets if doing so causes trivy to run out of memory?
* The program can (probably?) scan one file at a time without running out of memory, but it fails when it scans too many files at a time.  Is there a way to specify how many files to scan at a time?  
* A better approach would be to check how much memory has been allocated (assuming memory is freed at the end of each file scan), and use that value to decide to either wait or scan a new file.  This calculation should be done at the end of the individual file scans.
* The GNU `Parallel` program has solved this by calling an external command to decide whether the load, memory, io, or some custom metric is too high; see the `--limit` option.

**Comment by DmitriyLewen** [comment]
hmm... that's very strange.
Thank you very much for your investigation!
We will check it.

Regards, Dmitriy

**Comment by PenelopeFudd** [comment]
Thanks!

**Comment by Thesohan** [comment]
@PenelopeFudd @DmitriyLewen Is the out-of-memory issue resolved? Could you please share the details how did you fix it?

**Comment by DmitriyLewen** [comment]
Hello @Thesohan 

> Is the out-of-memory issue resolved? 

We are trying to improve our logic. And it looks like Trivy is working correctly now (I haven't seen an issue like this recently).

> Could you please share the details how did you fix it?

I can't send you specific PR's, because PR's weren't related to this issue (we fixed bugs, added new functionality, etc.).

If you are still having this issue (with the latest version of Trivy) - please let us know and we will investigate.

**Comment by Thesohan** [comment]
@DmitriyLewen Thanks for your quick response!

I'm facing this issue in v0.38.3.

I was skeptical about moving to the latest version of trivy as I couldn't find a fix for this issue in the changelogs.

Anyway, I'll move to the latest version and come back if I found it there.

Thanks!

**Comment by Mistikan** [comment]
I confirm the issue. I would like to set the upper memory limit and wait for the scan to complete successfully. Memory:
```
root@host:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           964Mi       564Mi       141Mi       1,0Mi       258Mi       252Mi
Swap:             0B          0B          0B

root@host:~# trivy version
Version: 0.65.0

```

**Solution** - add env:
```
GOMEMLIMIT="160MiB" 
```
