### ISSUE TITLE
CycloneDX output has badly formatted datetime strings

### ISSUE THREAD

**Issue by daniellawson** [aquasecurity/trivy#2026]
## Description

When using the cyclonedx output, the datetime strings include a three-letter TZ annotation, which isn't compliant with the cyclonedx spec.  Using the cyclonedx-cli (https://github.com/CycloneDX/cyclonedx-cli) to analyze the resulting output throws an exception regarding the format of the datetime, pointing to the additional three-letter timezone descriptor, eg "UTC".  

Trivy's cyclonedx output datetimes look like this:

```
"published":"2022-04-18 21:15:00 +0000 UTC"
```

The cyclonedx spec (https://github.com/CycloneDX/specification/blob/82bf9e30ba3fd6413e72a0e66adce2cdf3354f32/schema/bom-1.4.schema.json#L118) says this field is a date-time string, and the json spec (https://json-schema.org/understanding-json-schema/reference/string.html) says this should follow RFC3339 formatting (https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), which does not include "UTC"

Based on this, I think they should look like the following:

```
"published":"2022-04-18 21:15:00 +0000"
```

Removing all references to " UTC" (including the space) results in a file that the cyclonedx cli will parse correctly.

## What did you expect to happen?

Trivy's cyclonedx output will be accepted by tools that can read cyclonedx SBOMs, eg the cyclonedx-cli or Sonatype IQServer

## What happened instead?

The tools rejected trivy's cyclonedx SBOM with an exception pointing at a badly formatted datetime string.

## Output of run with `-debug`:

```
$ docker pull centos:7
$ trivy -debug image -o centos7-bom.json --format cyclonedx centos:7
2022-04-22T15:15:56.240+1200	DEBUG	'--format cyclonedx' automatically enables '--list-all-pkgs'.
2022-04-22T15:15:56.240+1200	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-04-22T15:15:56.248+1200	DEBUG	cache dir:  /home/daniel.lawson/.cache/trivy
2022-04-22T15:15:56.248+1200	DEBUG	DB update was skipped because the local DB is the latest
2022-04-22T15:15:56.248+1200	DEBUG	DB Schema: 2, UpdatedAt: 2022-04-22 00:12:01.313844571 +0000 UTC, NextUpdate: 2022-04-22 06:12:01.313844371 +0000 UTC, DownloadedAt: 2022-04-22 03:14:12.051392683 +0000 UTC
2022-04-22T15:15:56.249+1200	DEBUG	Vulnerability type:  [os library]
2022-04-22T15:15:56.253+1200	DEBUG	Image ID: sha256:eeb6ee3f44bd0b5103bb561b4c16bcb82328cfe5809ab675bb17ab3a16c517c9
2022-04-22T15:15:56.253+1200	DEBUG	Diff IDs: [sha256:174f5685490326fc0a1c0f5570b8663732189b327007e47ff13d2ca59673db02]
2022-04-22T15:15:56.256+1200	INFO	Detected OS: centos
2022-04-22T15:15:56.256+1200	INFO	Detecting RHEL/CentOS vulnerabilities...
2022-04-22T15:15:56.256+1200	DEBUG	Red Hat: os version: 7
2022-04-22T15:15:56.256+1200	DEBUG	Red Hat: the number of packages: 148
2022-04-22T15:15:56.307+1200	INFO	Number of language-specific files: 0
```

## Output of `trivy -v`:

```
$ trivy -v
Version: 0.26.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-04-20 00:10:37.635001046 +0000 UTC
  NextUpdate: 2022-04-20 06:10:37.635000446 +0000 UTC
  DownloadedAt: 2022-04-20 01:12:55.511569595 +0000 UTC
```

## Using cyclonedx-cli to analyze the trivy output:
```
$ ./cyclonedx-linux-x64 analyze --input-file ./centos7-bom.json --input-format json
Unhandled exception: System.FormatException: The string '2022-04-18 21:15:00 +0000 UTC' was not recognized as a valid DateTime. There is an unknown word starting at index '26'.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 , DateTimeFormatInfo , DateTimeStyles )
   at System.DateTime.Parse(String s)
   at CycloneDX.Json.Converters.DateTimeConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , TCollection& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter , Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& , Boolean , ReadOnlySpan`1 , JsonSerializerOptions , ReadStack& , JsonConverter )
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& , JsonReaderState& , ReadStack& , JsonConverter , JsonSerializerOptions )
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream , JsonTypeInfo , CancellationToken )
   at CycloneDX.Json.Serializer.DeserializeAsync(Stream jsonStream)
   at CycloneDX.Cli.CliUtils.InputBomHelper(String filename, CycloneDXBomFormat format)
   at CycloneDX.Cli.Commands.AnalyzeCommand.Analyze(AnalyzeCommandOptions options)
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

## Fixing up the trivy output and re-running through cyclonedx-cli:
```
$ sed 's/\ UTC//g' ./centos7-bom.json > fixed-centos7-bom.json 
$ ./cyclonedx-linux-x64 analyze --input-file ./fixed-centos7-bom.json --input-format json
Analysis results for centos:7@:
BOM Serial Number: urn:uuid:bc3201aa-f893-4005-856a-f78d0d46a221
BOM Version: 1
Timestamp: 22/04/2022 3:15:56 AM

```

[fixed-centos7-bom.json.txt](https://github.com/aquasecurity/trivy/files/8536605/fixed-centos7-bom.json.txt)
[centos7-bom.json.txt](https://github.com/aquasecurity/trivy/files/8536606/centos7-bom.json.txt)

**Comment by knqyf263** [comment]
Hi, thanks for raising an issue! We'll take a look. @afdesk Could you look into it?

**Comment by DavidJuanes** [comment]
I've also hit this issue while integrating trivy with Nexus IQ Server. 

After some research I can confirm few things:
- the attached fixed SBOM is still not valid. `cyclonedx-linux-x64 analyze ` is not the right command to validate the bom, instead if we use `validate` command we see the BOM is still invalid:
```
./cyclonedx.exe validate --input-file fixed-centos7-bom.json --input-version v1_4 --input-format json
Validating JSON BOM...
Validation failed:
#
BOM is not valid.
```
- I found that a valid time-date format would be `2022-03-31T16:29:00+0000`, so from the original time-date format:
    * Remove timezone abbreviation
    * remove spaces before the +
    * replace space between date and time with a `T`
Buggy date: `2022-04-18 21:15:00 +0000 UTC`
Fixed date: `2022-04-18T21:15:00+0000`

- The date-time is not the only invalid field in the SBOM generated by Trivy, I've also found that it generates `"cwes": null ` fields that are not valid in the bom1.4.schema. Removing `"cwes": null` fixes the issue.

- I've used https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/main/src/CycloneDX.Core/Schemas/bom-1.4.schema.json and https://www.jsonschemavalidator.net to easily validate my SBOM against the schema

**Comment by DmitriyLewen** [comment]
Hello @daniellawson @DavidJuanes 
Thanks a lot for detailed report!

We fixed this error.
Fix will be add in next Trivy release(in two weeks: https://github.com/aquasecurity/trivy/milestone/6) 

Best Regards, Dmitriy
