### ISSUE TITLE
CLI command ends in panic

### ISSUE THREAD

**Issue by DhritiShikhar** [aquasecurity/trivy#2087]
## Description

trivy CLI command line results in `panic` error instead of proper failure message.

```
➜  ~ trivy conf --severity HIGH go/src/github.com/openshift/external-dns-operator/
panic: interface conversion: interface {} is string, not bool

goroutine 1 [running]:
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Property).AsBool(0x2?)
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/defsec@v0.28.5-0.20220426090908-0df04f1fa28b/parsers/cloudformation/parser/property_helpers.go:144 +0x185
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Property).AsBoolValue(0xc0018b4000?)
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/defsec@v0.28.5-0.20220426090908-0df04f1fa28b/parsers/cloudformation/parser/property_helpers.go:148 +0x30
github.com/aquasecurity/defsec/adapters/cloudformation/aws/ec2.getBlockDevices(0xc0018da960?)
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/defsec@v0.28.5-0.20220426090908-0df04f1fa28b/adapters/cloudformation/aws/ec2/instance.go:58 +0xf6
github.com/aquasecurity/defsec/adapters/cloudformation/aws/ec2.getInstances({{0xc00021a7e0, 0x70}, {0xc000c33000, 0xe3, 0xe3}, {0x1d58351, 0x4}, 0xc0017214d0, 0xc0017216b0, 0x0, ...})
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/defsec@v0.28.5-0.20220426090908-0df04f1fa28b/adapters/cloudformation/aws/ec2/instance.go:28 +0x81a
github.com/aquasecurity/defsec/adapters/cloudformation/aws/ec2.Adapt(...)
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/defsec@v0.28.5-0.20220426090908-0df04f1fa28b/adapters/cloudformation/aws/ec2/ec2.go:11
github.com/aquasecurity/defsec/adapters/cloudformation/aws.Adapt({{0xc00021a7e0, 0x70}, {0xc000c33000, 0xe3, 0xe3}, {0x1d58351, 0x4}, 0xc0017214d0, 0xc0017216b0, 0x0, ...})
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/defsec@v0.28.5-0.20220426090908-0df04f1fa28b/adapters/cloudformation/aws/adapt.go:56 +0x918
github.com/aquasecurity/defsec/adapters/cloudformation.Adapt(...)
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/defsec@v0.28.5-0.20220426090908-0df04f1fa28b/adapters/cloudformation/adapt.go:12
github.com/aquasecurity/defsec/scanners/cloudformation/scanner.(*Scanner).Scan(0xc0012ee300, {0x227e1f0, 0xc000f411a0})
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/defsec@v0.28.5-0.20220426090908-0df04f1fa28b/scanners/cloudformation/scanner/scanner.go:108 +0x278
github.com/aquasecurity/fanal/config/scanner.Scanner.scanCloudFormation({{0x7ffc6223f252, 0x32}, {0xc000761b80, 0x2, 0x2}, 0xc0008df4c0, 0xc001338fc0, 0xc0012ee300}, {0x227e1f0, 0xc000f411a0}, ...)
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220430134203-bc6fd26a109e/config/scanner/scanner.go:151 +0x2a6
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs({{0x7ffc6223f252, 0x32}, {0xc000761b80, 0x2, 0x2}, 0xc0008df4c0, 0xc001338fc0, 0xc0012ee300}, {0x227e1f0, 0xc000f411a0}, ...)
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220430134203-bc6fd26a109e/config/scanner/scanner.go:97 +0x47b
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect({{0x7ffc6223f252, 0x31}, {0x7fb5643fd7d8, 0xc0008e10b0}, {{{0x0, 0x0, 0x0}, {0xc0008dfe00, 0x3, 0x4}}}, ...}, ...)
	/home/dhritishikhar/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220430134203-bc6fd26a109e/artifact/local/fs.go:120 +0x345
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0x0, 0x0, 0x0}, {0xc0008e0ff0, ...}, ...})
	/home/dhritishikhar/Documents/trivy/pkg/scanner/scan.go:110 +0x103
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{0xc000763040, 0xc0005d8090, {0x226d550, 0x14}, 0x0, 0x0, {0xc001312160, 0x20}}, ...}, ...)
	/home/dhritishikhar/Documents/trivy/pkg/commands/artifact/run.go:272 +0x99e
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout({_, _}, {{0xc000763040, 0xc0005d8090, {0x226d550, 0x14}, 0x0, 0x0, {0xc001312160, 0x20}}, ...}, ...)
	/home/dhritishikhar/Documents/trivy/pkg/commands/artifact/run.go:90 +0x48c
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{0xc000763040, 0xc0005d8090, {0x226d550, 0x14}, 0x0, 0x0, {0xc001312160, 0x20}}, ...}, ...)
	/home/dhritishikhar/Documents/trivy/pkg/commands/artifact/run.go:58 +0xca
github.com/aquasecurity/trivy/pkg/commands/artifact.ConfigRun(0xc000763040)
	/home/dhritishikhar/Documents/trivy/pkg/commands/artifact/config.go:29 +0x2af
github.com/urfave/cli/v2.(*Command).Run(0xc0012d1680, 0xc000762900)
	/home/dhritishikhar/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc0005831e0, {0x227e1b8?, 0xc0001aa020}, {0xc000180050, 0x5, 0x5})
	/home/dhritishikhar/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
	/home/dhritishikhar/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.main()
	/home/dhritishikhar/Documents/trivy/cmd/trivy/main.go:16 +0x4f

```

## What did you expect to happen?

A proper error message in output

## What happened instead?

Golang error

## Output of run with `-debug`:

```
➜  ~ trivy conf --severity HIGH go/src/github.com/openshift/external-dns-operator/ -debug
2022-05-05T16:04:51.451+0530	ERROR	multiple targets cannot be specified
2022-05-05T16:04:51.451+0530	FATAL	option error: option initialize error: arguments error

```

## Output of `trivy -v`:

```
➜  ~ trivy -v                                                                            
Version: v0.27.1-13-gfa5dcaf8
```

**Comment by DmitriyLewen** [comment]
Hello @DhritiShikhar 
Thanks for your report!

Are you using custom version of Trivy?
Main branch doesn't contain `gfa5dcaf8` commit, and Trivy doesn't create  version like yours, If i remember correctly.

Regards, Dmitriy

**Comment by DmitriyLewen** [comment]
@DhritiShikhar Main branch may not be stable to use.
Can you try installing Trivy v0.28.0 using this [guide](https://aquasecurity.github.io/trivy/v0.28.0/getting-started/installation/) and check again?

**Comment by dAnjou** [comment]
I'm experiencing something similar and did a bit more debugging.
```
Version: 0.28.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-05-19 06:07:16.611103192 +0000 UTC
  NextUpdate: 2022-05-19 12:07:16.611102992 +0000 UTC
  DownloadedAt: 2022-05-19 08:15:15.377149 +0000 UTC
```
`secrets.tf`:
```
resource "aws_secretsmanager_secret" "foo" {

}
```
```
trivy config secrets.tf # succeeds
```
```
2022-05-24T14:21:47.653+0200	INFO	Detected config files: 1

secrets.tf (terraform)

Tests: 1 (SUCCESSES: 0, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

LOW: Secret explicitly uses the default key.
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Secrets Manager encrypts secrets by default using a default key created by AWS. To ensure control and granularity of secret encryption, CMK's should be used explicitly.

See https://avd.aquasec.com/misconfig/avd-aws-0098
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 secrets.tf:1-3
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 ┌ resource "aws_secretsmanager_secret" "foo" {
   2 │
   3 └ }
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
```
trivy config --severity LOW secrets.tf # succeeds
```
```
2022-05-24T14:24:53.530+0200	INFO	Detected config files: 1

secrets.tf (terraform)

Tests: 1 (SUCCESSES: 0, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (LOW: 1)

LOW: Secret explicitly uses the default key.
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Secrets Manager encrypts secrets by default using a default key created by AWS. To ensure control and granularity of secret encryption, CMK's should be used explicitly.

See https://avd.aquasec.com/misconfig/avd-aws-0098
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 secrets.tf:1-3
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 ┌ resource "aws_secretsmanager_secret" "foo" {
   2 │
   3 └ }
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
```
trivy config --format json --severity MEDIUM secrets.tf # succeeds
```
```
2022-05-24T14:26:18.902+0200	INFO	Detected config files: 1
{
  "SchemaVersion": 2,
  "ArtifactName": "secrets.tf",
  "ArtifactType": "filesystem",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "secrets.tf",
      "Class": "config",
      "Type": "terraform"
    }
  ]
}
```
```
trivy config --severity MEDIUM secrets.tf # FAILS
```
```
2022-05-24T14:26:00.212+0200	INFO	Detected config files: 1

secrets.tf (terraform)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101f2a4ec]

goroutine 1 [running]:
github.com/aquasecurity/trivy/pkg/report.TableWriter.write({{0x1400065e000, 0x1, 0x1}, {0x103f56bb8, 0x140001a4008}, 0x14001da6fa0, 0x0, 0x0}, {{0x14001da6cf0, 0xa}, ...})
	github.com/aquasecurity/trivy/pkg/report/table.go:107 +0x56c
github.com/aquasecurity/trivy/pkg/report.TableWriter.Write(...)
	github.com/aquasecurity/trivy/pkg/report/table.go:48
github.com/aquasecurity/trivy/pkg/report.Write({0x2, {0x16ef27007, 0xa}, {0x1030e1ec5, 0xa}, {0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/report/writer.go:73 +0x50c
github.com/aquasecurity/trivy/pkg/commands/artifact.(*Runner).Report(_, {{0x140016ff900, 0x14000011888, {0x1038497c8, 0x6}, 0x0, 0x0, {0x140005573e0, 0x1e}}, {{0x0, ...}, ...}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:210 +0xf4
github.com/aquasecurity/trivy/pkg/commands/artifact.run({_, _}, {{0x140016ff900, 0x14000011888, {0x1038497c8, 0x6}, 0x0, 0x0, {0x140005573e0, 0x1e}}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:343 +0xa5c
github.com/aquasecurity/trivy/pkg/commands/artifact.ConfigRun(0x140016ff900)
	github.com/aquasecurity/trivy/pkg/commands/artifact/config.go:26 +0x1f8
github.com/urfave/cli/v2.(*Command).Run(0x1400110ad80, 0x140016ff1c0)
	github.com/urfave/cli/v2@v2.5.1/command.go:163 +0x50c
github.com/urfave/cli/v2.(*App).RunContext(0x14000532680, {0x103f73b30?, 0x140001a8008}, {0x1400018e050, 0x5, 0x5})
	github.com/urfave/cli/v2@v2.5.1/app.go:313 +0x888
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.5.1/app.go:224
main.main()
	github.com/aquasecurity/trivy/cmd/trivy/main.go:16 +0x5c
```
So, it seems it only fails for the `table` format and only when you're filtering for a severity that doesn't contain any results.

**Comment by DmitriyLewen** [comment]
Thanks a lot for this great answer.

I will check and write to you.

Regards, Dmitriy

**Comment by dAnjou** [comment]
Thanks for fixing this so fast! Can I expect a new release soon?

**Comment by knqyf263** [comment]
yes, in two weeks
https://github.com/aquasecurity/trivy/milestone/6
