### ISSUE TITLE
Trivi crashes while scanning AWS

### ISSUE THREAD

**Issue by pritammobisoft** [aquasecurity/trivy#2723]
Running in WSL 2 (Ubuntu 20.04.3 LTS).
Executable used: trivy_0.31.0_Linux-64bit.tar.gz

Command and output

```
./trivy aws --region us-east-1
[1/31] Scanning api-gateway...
[2/31] Scanning athena...
[3/31] Scanning cloudfront...
[4/31] Scanning cloudtrail...
[5/31] Scanning cloudwatch...
[6/31] Scanning codebuild...
[7/31] Scanning documentdb...
[8/31] Scanning dynamodb...
[9/31] Scanning ec2...
[10/31] Scanning ecr...
[11/31] Scanning ecs...
[12/31] Scanning efs...
[13/31] Scanning eks...
[14/31] Scanning elasticache...
[15/31] Scanning elasticsearch...
[16/31] Scanning elb...
└╴Adapting load balancers... ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒   0% 0/1 ??/s ETA: ??m??s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x25fac9c]

goroutine 865 [running]:
github.com/aquasecurity/defsec/internal/adapters/cloud/aws/elb.(*adapter).adaptLoadBalancer(0xc0003280d0, {{0xc005858ee0, 0x4, 0x4}, 0xc0006ad4b0, 0xc0005a5038, 0x0, 0xc0006ad470, {0xc000ff29d4, 0x4}, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.71.5/internal/adapters/cloud/aws/elb/adapt.go:111 +0x57c
github.com/aquasecurity/defsec/pkg/concurrency.Adapt[...].func1(0x0)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.71.5/pkg/concurrency/adapter.go:18 +0x57
github.com/aquasecurity/defsec/pkg/concurrency.AdaptWithState[...].func1()
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.71.5/pkg/concurrency/adapter.go:42 +0x189
created by github.com/aquasecurity/defsec/pkg/concurrency.AdaptWithState[...]
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.71.5/pkg/concurrency/adapter.go:35 +0x1c7
```

**Comment by belambic** [comment]
I got the same error running on PopOs using the .deb

**Comment by becelot** [comment]
Same here. Using MacOS ARM64

**Comment by nilicule** [comment]
Same here, though in a different component, using MacOS ARM64

**Comment by owenrumney** [comment]
We have a fix for this, will be released shortly

**Comment by owenrumney** [comment]
https://github.com/aquasecurity/trivy/pull/2720
