### ISSUE TITLE
Trivy seems to crash when scanning --service workspaces

### ISSUE THREAD

**Issue by xxradar** [aquasecurity/trivy#2739]
## Description
Trivy seems to crash when scanning --service workspaces

$ trivy aws --region eu-west-3 --service workspaces --debug
2022-08-17T20:27:43.471Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-08-17T20:27:43.472Z	DEBUG	Timeout is set to less than 1 hour - upgrading to 1 hour for this command.
2022-08-17T20:27:43.472Z	DEBUG	Looking for AWS credentials provider...
2022-08-17T20:27:43.472Z	DEBUG	Looking up AWS caller identity...
2022-08-17T20:27:43.514Z	DEBUG	Verified AWS credentials for account 974654858447!
2022-08-17T20:27:43.515Z	DEBUG	Specific services were requested: [workspaces]...
2022-08-17T20:27:43.530Z	DEBUG	Scanning the following services using the AWS API: [workspaces]...
2022-08-17T20:27:43.531Z	DEBUG	[defsec] 27:43.531566909 aws-api.scanner.adapt.aws        Using region 'eu-west-3'
2022-08-17T20:27:43.531Z	DEBUG	[defsec] 27:43.531799036 aws-api.scanner.adapt.aws        Discovering caller identity...
2022-08-17T20:27:43.551Z	DEBUG	[defsec] 27:43.551552165 aws-api.scanner.adapt.aws        AWS account ID: 974654858447
2022-08-17T20:27:43.551Z	DEBUG	[defsec] 27:43.551831944 aws-api.scanner.adapt.aws        Preparing to run for 1 filtered services...
2022-08-17T20:27:43.552Z	DEBUG	[defsec] 27:43.552090957 aws-api.scanner.adapt.aws        Running adapter for workspaces...
[1/1] Scanning workspaces...
└╴Discovering workspaces... ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ???% 0/0 ??/s ETA: ??m??s
2022-08-17T20:27:47.415Z	DEBUG	[defsec] 27:47.415019822 aws-api.scanner.adapt.aws        Error occurred while running adapter for workspaces: operation error WorkSpaces: DescribeWorkspaces, exceeded maximum number
2022-08-17T20:27:47.415Z	DEBUG	[defsec] 27:47.415137863 aws-api.scanner                  There were 1 errors during adaption process: failed to run adapter for workspaces: operation error WorkSpaces: DescribeWorkspaces, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "https://workspaces.eu-west-3.amazonaws.com/": dial tcp: lookup workspaces.eu-west-3.amazonaws.com on 127.0.0.53:53: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3cb6eda]

goroutine 1 [running]:
github.com/aquasecurity/defsec/internal/rules/aws/apigateway.glob..func1(0x0)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.71.5/internal/rules/aws/apigateway/enable_access_logging.go:39 +0x5a
github.com/aquasecurity/defsec/internal/rules.RegisteredRule.Evaluate({0x0, {{0x6ddd649, 0xc}, {0x0, 0x0, 0x0}, {0x6e428b3, 0x15}, {0x6f74278, 0x43}, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.71.5/internal/rules/register.go:25 +0x3b
github.com/aquasecurity/defsec/pkg/scanners/cloud/aws.(*Scanner).Scan(0xc00586c280, {0x7e5f268, 0xc004a4f6e0})
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.71.5/pkg/scanners/cloud/aws/scanner.go:101 +0x42a
github.com/aquasecurity/trivy/pkg/cloud/aws/scanner.(*AWSScanner).Scan(_, {_, _}, {{{0x6dcbff8, 0xa}, 0x0, 0x0, 0x1, 0x0, 0x34630b8a000, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/cloud/aws/scanner/scanner.go:60 +0x59a
github.com/aquasecurity/trivy/pkg/cloud/aws/commands.Run({_, _}, {{{0x6dcbff8, 0xa}, 0x0, 0x0, 0x1, 0x0, 0x34630b8a000, {0xc003b902a0, ...}, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/cloud/aws/commands/run.go:146 +0x3ce
github.com/aquasecurity/trivy/pkg/commands.NewAWSCommand.func2(0xc00482ec80, {0xc00460fc70?, 0x5?, 0x5?})
	/home/runner/work/trivy/trivy/pkg/commands/app.go:844 +0x1bb
github.com/spf13/cobra.(*Command).execute(0xc00482ec80, {0xc00460fc20, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc004635400)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.run()
	/home/runner/work/trivy/trivy/cmd/trivy/main.go:37 +0x17c
main.main()
	/home/runner/work/trivy/trivy/cmd/trivy/main.go:19 +0x19

## Output of `trivy -v`:

```
Version: 0.31.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-05-06 06:06:39.013621652 +0000 UTC
  NextUpdate: 2022-05-06 12:06:39.013621252 +0000 UTC
  DownloadedAt: 2022-05-06 08:31:22.893702944 +0000 UT
```

## Additional details (base image name, container registry info...):
Running on 
Linux ip-10-1-1-52 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by owenrumney** [comment]
@xxradar  - this should be resolved in the latest release. Could you try with v0.31.2?

**Comment by matt4biz** [comment]
in v0.31.2 it doesn't crash, but still warns when targeting a region without workspaces, such as us-east-2:

```
[31/31] Scanning workspaces...
2022-08-18T21:05:48.850-0500	WARN	Adapter error: failed to run adapter for workspaces: operation error WorkSpaces: DescribeWorkspaces, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "https://workspaces.us-east-2.amazonaws.com/": dial tcp: lookup workspaces.us-east-2.amazonaws.com on 192.168.254.254:53: no such host
```

and then all the vulnerability counts are 0, which is suspicious

**Comment by xxradar** [comment]
Same behaviour in v0.31.2
```
[30/31] Scanning ssm...
[31/31] Scanning workspaces...
2022-08-26T19:16:27.448Z	WARN	Adapter error: failed to run adapter for workspaces: operation error WorkSpaces: DescribeWorkspaces, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "https://workspaces.eu-west-3.amazonaws.com/": dial tcp: lookup workspaces.eu-west-3.amazonaws.com on 127.0.0.53:53: no such host```

+all the vulnerability counts are 0

**Comment by pritam-yadu** [comment]
This is still giving error in some regions. I am using 0.31.3. 

`
![image](https://user-images.githubusercontent.com/100335945/212054171-52e7daeb-7daa-408e-8fb0-500ecd85afab.png)
`
