### ISSUE TITLE
Panic in config scan of cloudformation when IAM policy contains If

### ISSUE THREAD

**Issue by pheck** [aquasecurity/trivy#2898]
## Description
When running a config scan against cloudformation yaml templates, trivy crashes with the below error. 

## What did you expect to happen?
Trivy scan finishes and outputs scan results

## What happened instead?
Trivy crashes when processing a cloudformation template with an IAM-role whose `Policies` section contains an `!If` function.

## Output of run with `-debug`:

```
❯ trivy -d config .
2022-09-16T15:34:47.745+0200	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-09-16T15:34:47.798+0200	DEBUG	cache dir:  /Users/{REDACTED}/Library/Caches/trivy
2022-09-16T15:34:47.798+0200	INFO	Misconfiguration scanning is enabled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e5fe3d]

goroutine 1 [running]:
github.com/aquasecurity/defsec/pkg/scanners/cloudformation/parser.(*Property).AsRawStrings(0x0)
	github.com/aquasecurity/defsec@v0.71.9/pkg/scanners/cloudformation/parser/property.go:149 +0x1d
github.com/aquasecurity/defsec/pkg/scanners/cloudformation/parser.(*Property).GetJsonBytes(0x0, {0x0?, 0x0, 0x0?})
	github.com/aquasecurity/defsec@v0.71.9/pkg/scanners/cloudformation/parser/property.go:361 +0x32
github.com/aquasecurity/defsec/internal/adapters/cloudformation/aws/iam.getPoliciesDocs(0xc001df2050?)
	github.com/aquasecurity/defsec@v0.71.9/internal/adapters/cloudformation/aws/iam/policy.go:109 +0xe9
github.com/aquasecurity/defsec/internal/adapters/cloudformation/aws/iam.getRoles({{0xc002edc3a8, 0x16}, {0xc00391c000, 0x1a2, 0x1a2}, {0xaf654d1, 0x4}, 0xc00473e150, 0xc00473e5a0, 0x0, ...})
	github.com/aquasecurity/defsec@v0.71.9/internal/adapters/cloudformation/aws/iam/policy.go:44 +0x3b0
github.com/aquasecurity/defsec/internal/adapters/cloudformation/aws/iam.Adapt({{0xc002edc3a8, 0x16}, {0xc00391c000, 0x1a2, 0x1a2}, {0xaf654d1, 0x4}, 0xc00473e150, 0xc00473e5a0, 0x0, ...})
	github.com/aquasecurity/defsec@v0.71.9/internal/adapters/cloudformation/aws/iam/iam.go:25 +0x95e
github.com/aquasecurity/defsec/internal/adapters/cloudformation/aws.Adapt({{0xc002edc3a8, 0x16}, {0xc00391c000, 0x1a2, 0x1a2}, {0xaf654d1, 0x4}, 0xc00473e150, 0xc00473e5a0, 0x0, ...})
	github.com/aquasecurity/defsec@v0.71.9/internal/adapters/cloudformation/aws/adapt.go:55 +0x5e5
github.com/aquasecurity/defsec/internal/adapters/cloudformation.Adapt(...)
	github.com/aquasecurity/defsec@v0.71.9/internal/adapters/cloudformation/adapt.go:12
github.com/aquasecurity/defsec/pkg/scanners/cloudformation.(*Scanner).scanFileContext(0xc001b91a40, {0xc0a2b20, 0xc001b747e0}, 0xc0018a3500?, 0xc0034d7620, {0xc01e560, 0xc001e3c018})
	github.com/aquasecurity/defsec@v0.71.9/pkg/scanners/cloudformation/scanner.go:170 +0xd8
github.com/aquasecurity/defsec/pkg/scanners/cloudformation.(*Scanner).ScanFS(0xc001b91a40, {0xc0a2b20, 0xc001b747e0}, {0xc01e560, 0xc001e3c018}, {0xbff81f6?, 0x0?})
	github.com/aquasecurity/defsec@v0.71.9/pkg/scanners/cloudformation/scanner.go:133 +0x1ba
github.com/aquasecurity/trivy/pkg/fanal/handler/misconf.misconfPostHandler.Handle({{0xf7c68c0?, 0xf7c9da0?, 0xc00226a9d8?}, 0xc0043eeed0?}, {0xc0a2b20, 0xc001b747e0}, 0x2f40?, 0xc001d50000)
	github.com/aquasecurity/trivy/pkg/fanal/handler/misconf/misconf.go:282 +0x46b
github.com/aquasecurity/trivy/pkg/fanal/handler.Manager.PostHandle({{0xc00496b200?, 0x0?, 0x0?}}, {0xc0a2b20, 0xc001b747e0}, 0x4?, 0x7ffeefbff9b8?)
	github.com/aquasecurity/trivy/pkg/fanal/handler/handler.go:74 +0xaf
github.com/aquasecurity/trivy/pkg/fanal/artifact/local.Artifact.Inspect({{0x7ffeefbff9b8, 0x1}, {0x1b534c98, 0xc001d89ac0}, {{{0x0, 0x0, 0x0}, {0xc00496b240, 0x3, 0x4}}}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/fanal/artifact/local/fs.go:126 +0x458
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0x0, 0x0, 0x0}, {0xc001d899a0, ...}, ...})
	github.com/aquasecurity/trivy/pkg/scanner/scan.go:125 +0xeb
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{{0xaf99ef8, 0xa}, 0x0, 0x0, 0x1, 0x0, 0x45d964b800, {0xc003484360, ...}, ...}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:539 +0x3df
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact(_, {_, _}, {{{0xaf99ef8, 0xa}, 0x0, 0x0, 0x1, 0x0, 0x45d964b800, ...}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:228 +0xcb
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanFS(_, {_, _}, {{{0xaf99ef8, 0xa}, 0x0, 0x0, 0x1, 0x0, 0x45d964b800, ...}, ...})
	github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:201 +0xc5
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).ScanFilesystem(_, {_, _}, {{{0xaf99ef8, 0xa}, 0x0, 0x0, 0x1, 0x0, 0x45d964b800, ...}, ...})
	github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:181 +0x1e5
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{{0xaf99ef8, 0xa}, 0x0, 0x0, 0x1, 0x0, 0x45d964b800, {0xc003484360, ...}, ...}, ...}, ...)
	github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:373 +0x36d
github.com/aquasecurity/trivy/pkg/commands.NewConfigCommand.func2(0xc0018ef400, {0xc00433a5e0, 0x1, 0x2})
	github.com/aquasecurity/trivy/pkg/commands/app.go:572 +0x2fe
github.com/spf13/cobra.(*Command).execute(0xc0018ef400, {0xc00433a5c0, 0x2, 0x2})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0018ee280)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.run()
	github.com/aquasecurity/trivy/cmd/trivy/main.go:37 +0x177
main.main()
	github.com/aquasecurity/trivy/cmd/trivy/main.go:19 +0x19
```

## Output of `trivy -v`:

```
Version: 0.31.3
```

## Additional details (base image name, container registry info...):

Cloudformation template snippet that causes the error.
When the `>>>marked` lines are removed, the trivy config scan is successful again.

```
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
>>>     - !If
>>>       - HasEnableExecuteCommand
          - PolicyName: "allow-ecs-exec"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: [
                      "ssmmessages:CreateControlChannel",
                      "ssmmessages:CreateDataChannel",
                      "ssmmessages:OpenControlChannel",
                      "ssmmessages:OpenDataChannel"]
                  Resource: "*"
>>>       - !Ref AWS::NoValue
```

**Comment by knqyf263** [comment]
@simar7 Could you take a look?

**Comment by itaysk** [comment]
seems to be same as https://github.com/aquasecurity/trivy/issues/3418

**Comment by jackroberts-gh** [comment]
Also seeing issues with CloudFormation processing with trivy when using `If` statements. Results in a panic.

`trivy config --format template --template "@/tmp/junit.tpl" --skip-dirs node_modules,deployment --config .trivy .
2023-03-13T20:18:19.994Z        INFO    Loaded .trivy
2023-03-13T20:18:20.003Z        INFO    Misconfiguration scanning is enabled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x78 pc=0x106743954]

goroutine 1 [running]:
github.com/aquasecurity/defsec/pkg/scanners/cloudformation/parser.(*Property).AsStringValue(0x14000d4a300?)`

Using trivy 0.31.3
