### ISSUE TITLE
`go get` fails with a panic

### ISSUE THREAD

**Issue by mattyclarkson** [aquasecurity/trivy#3802]
## Description

```
mkdir /tmp/test
cd /tmp/test
go init some.com/test
go get github.com/aquasecurity/trivy/cmd/trivy@v0.38.2
go build -o trivy github.com/aquasecurity/trivy/cmd/trivy
```

End up with a panic in the `go get` step.

```
panic: internal error: can't find reason for requirement on github.com/gregjones/httpcache@v0.0.0-20180305231024-9cad4c3443a7
```

## What did you expect to happen?

`go get` to complete.

## What happened instead?

```
panic: internal error: can't find reason for requirement on github.com/gregjones/httpcache@v0.0.0-20180305231024-9cad4c3443a7
goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc003a5dee0, 0x1e}, {0xc000225920, 0x22}})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0xd4
cmd/go/internal/modget.(*resolver).updateBuildList(0xc000154000, {0xb3bd58, 0xc0000a8000}, {0x0, 0x0, 0x0})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x54c
cmd/go/internal/modget.(*resolver).applyUpgrades(0xc000154000, {0xb3bd58, 0xc0000a8000}, {0x0?, 0x0, 0xc0000afd70?})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1312 +0x465
cmd/go/internal/modget.runGet({0xb3bd58, 0xc0000a8000}, 0xc0000d0450?, {0xc0000a4170, 0x1, 0x1})
	/usr/local/go/src/cmd/go/internal/modget/get.go:351 +0x458
main.invoke(0xe52240, {0xc0000a4160, 0x2, 0x2})
	/usr/local/go/src/cmd/go/main.go:225 +0x3d9
main.main()
	/usr/local/go/src/cmd/go/main.go:179 +0x7ce
```

## Additional details (base image name, container registry info...):

```
$ go version
go version go1.19.4 linux/amd64
```

**Comment by knqyf263** [comment]
Trivy is distributed as binaries. Using Trivy as a library is out of scope now.
https://aquasecurity.github.io/trivy/v0.38/getting-started/installation/

**Comment by mattyclarkson** [comment]
OK. Was trying to use `go get` to download the source. My misunderstanding about the `go` ecosystem.

I got confused because `go install https://github.com/aquasecurity/trivy/cmd/trivy@v0.38.2` failed due to replacements in the `go.mod`.

```
git clone --depth 1 --branch v0.38.2 https://github.com/aquasecurity/trivy
cd trivy
go install
```

That results in:

```
$ go install
no Go files in /tmp/trivy
```

Needs updating to:

```
cd trivy/cmd/trivy
```
