### ISSUE TITLE
Trivy started failing with: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by atodorov** [aquasecurity/trivy#3996]
## Description

I am using Trivy as part of MegaLinter. 

2 weeks ago Trivy was reporting a number of CVEs against my repository, see https://github.com/gluwa/creditcoin/actions/runs/4504152148/jobs/7928261090

I've upgraded all of the dependencies during that time and today I've rebased my PR which enables Trivy/MegaLinter, see https://github.com/gluwa/creditcoin/pull/899, in order to inspect what would be the latest status. 

Today Trivy started failing with a traceback:

```
panic: assignment to entry in nil map
  
  goroutine 1 [running]:
  golang.org/x/exp/maps.Copy[...](0xc0024c17d0?, 0x7520984?)
  	/home/runner/go/pkg/mod/golang.org/x/exp@v0.0.0-20220823124025-807a23277127/maps/maps.go:83 +0xab
  github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/rust/cargo.cargoAnalyzer.parseCargoTOML({{0xc0011f26c8?, 0xc0011f24d0?}, {}}, {0x88fd020?, 0xc0009248a8?}, {0xc00088e1f0?, 0x5?})
  	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/language/rust/cargo/cargo.go:187 +0x350
  github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/rust/cargo.cargoAnalyzer.removeDevDependencies({{0x88fcf20?, 0xbad0b08?}, {}}, {0x88fd020, 0xc0009248a8}, {0x88f1c82?, 0x88fcf20?}, 0xc002207140)
  	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/language/rust/cargo/cargo.go:108 +0xf6
  github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/rust/cargo.cargoAnalyzer.PostAnalyze.func2({0xc001725d60, 0xa}, {0xc000924908?, 0x0?}, {0x89988e0?, 0xc000924908?})
  	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/language/rust/cargo/cargo.go:72 +0x11c
  github.com/aquasecurity/trivy/pkg/utils/fsutils.WalkDir.func1({0xc001725d60, 0xa}, {0x899cf38, 0xc000ff3090}, {0x0?, 0x0?})
  	/home/runner/work/trivy/trivy/pkg/utils/fsutils/fs.go:106 +0x2ec
  io/fs.walkDir({0x88fd020, 0xc0009248a8}, {0xc001725d60, 0xa}, {0x899cf38, 0xc000ff3090}, 0xc0011f2f50)
  	/opt/hostedtoolcache/go/1.19.7/x64/src/io/fs/walk.go:65 +0x78
  io/fs.walkDir({0x88fd020, 0xc0009248a8}, {0x88f1c82, 0x1}, {0x899eeb8, 0xc001b284a0}, 0xc0011f2f50)
  	/opt/hostedtoolcache/go/1.19.7/x64/src/io/fs/walk.go:87 +0x2e7
  io/fs.WalkDir({0x88fd020, 0xc0009248a8}, {0x88f1c82, 0x1}, 0xc0011f2f50)
  	/opt/hostedtoolcache/go/1.19.7/x64/src/io/fs/walk.go:114 +0xde
  github.com/aquasecurity/trivy/pkg/utils/fsutils.WalkDir({0x88fd020?, 0xc0009248a8?}, {0x88f1c82?, 0xc0016827e0?}, 0xfb0000c0006ce703?, 0x0?)
  	/home/runner/work/trivy/trivy/pkg/utils/fsutils/fs.go:88 +0x5f
  github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/rust/cargo.cargoAnalyzer.PostAnalyze({{0x88fcf20?, 0xbad0b08?}, {}}, {0xc00179ebd0?, 0x68000c0?}, {{0x88fd020?, 0xc0009248a8?}, {0x5?, 0x0?}})
  	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/language/rust/cargo/cargo.go:62 +0xd3
  github.com/aquasecurity/trivy/pkg/fanal/analyzer.AnalyzerGroup.PostAnalyze({{0xc0012d6000, 0x26, 0x40}, {0xc000176980, 0x6, 0x8}, 0xc00179eae0}, {0x899c0c8, 0xc0009d7c80}, 0xc00179ebd0, ...)
  	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/analyzer.go:482 +0x14f
  github.com/aquasecurity/trivy/pkg/fanal/artifact/local.Artifact.Inspect({{0x7ffdf115acb2, 0x1}, {0x7f256befe110, 0xc000e004f0}, {{{0x0, 0x0, 0x0}, {0xc001013300, 0x3, 0x4}, ...}}, ...}, ...)
  	/home/runner/work/trivy/trivy/pkg/fanal/artifact/local/fs.go:163 +0x407
  github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0xc0001d84a0, 0x2, 0x2}, {0xc0001d8180, ...}, ...})
  	/home/runner/work/trivy/trivy/pkg/scanner/scan.go:144 +0x103
  github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{{0x7508f27, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x45d964b800, {0xc0018ee8e0, ...}, ...}, ...}, ...)
  	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:677 +0x377
  github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact(_, {_, _}, {{{0x7508f27, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x45d964b800, ...}, ...}, ...)
  	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:264 +0xbc
  github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanFS(_, {_, _}, {{{0x7508f27, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x45d964b800, ...}, ...})
  	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:213 +0xd1
  github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).ScanFilesystem(_, {_, _}, {{{0x7508f27, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x45d964b800, ...}, ...})
  	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:193 +0x1db
  github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{{0x7508f27, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x45d964b800, {0xc0018ee8e0, ...}, ...}, ...}, ...)
  	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:430 +0x4e3
  github.com/aquasecurity/trivy/pkg/commands.NewFilesystemCommand.func2(0xc0001c9800, {0xc00010f680, 0x1, 0x5})
  	/home/runner/work/trivy/trivy/pkg/commands/app.go:339 +0x21e
  github.com/spf13/cobra.(*Command).execute(0xc0001c9800, {0xc00010f630, 0x5, 0x5})
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
  github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c8c00)
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
  github.com/spf13/cobra.(*Command).Execute(...)
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
  main.run()
  	/home/runner/work/trivy/trivy/cmd/trivy/main.go:39 +0x177
  main.main()
  	/home/runner/work/trivy/trivy/cmd/trivy/main.go:21 +0x19
```

Reported first against MegaLinter in https://github.com/oxsecurity/megalinter/issues/2526 but they say that's new to them and refer me to open an issue here.

## What did you expect to happen?

Trivy would not crash but produce a report

## What happened instead?

Trivy crashed

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
trivy v0.39.0
```

## Additional details (base image name, container registry info...):

Full log at https://github.com/gluwa/creditcoin/actions/runs/4617103427/jobs/8162938177?pr=899

**Comment by DmitriyLewen** [comment]
Hello @atodorov 
Thanks for your report!

We created #3997 to fix this bug.
After merge this PR we will include changes to next release.

Regards, Dmitriy!

**Comment by knqyf263** [comment]
v0.39.1 includes this fix.
