### ISSUE TITLE
Alpine Linux s390x - make test segfault

### ISSUE THREAD

**Issue by TBK** [aquasecurity/trivy#430]
**Description**
I am working on packaging trivy for Alpine Linux and as part of the build process run the tests (make test). Unfortunately there is a segfault on s390x.

**Build log:**
```
ok  	github.com/aquasecurity/trivy/pkg/rpc/client	0.015s
=== RUN   Test_dbWorker_update
=== RUN   Test_dbWorker_update/happy_path
2020-03-07T09:58:18.897Z	INFO	Updating DB...
2020-03-07T09:58:18.897Z	INFO	Suspending all requests during DB update
2020-03-07T09:58:18.897Z	INFO	Waiting for all requests to be processed before DB update...
2020-03-07T09:58:18.897Z	INFO	Reopening DB...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aa2211f13e]
goroutine 53 [running]:
testing.tRunner.func1(0xc000182b00)
	/usr/lib/go/src/testing/testing.go:874 +0x41a
panic(0x2aa22e20b40, 0x2aa236ef420)
	/usr/lib/go/src/runtime/panic.go:679 +0x1d4
github.com/etcd-io/bbolt.(*DB).beginTx(0x0, 0x3000, 0x3000, 0x3000)
	/home/buildozer/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:551 +0x1e
github.com/etcd-io/bbolt.(*DB).Begin(0x0, 0x2aa22a3c0ae, 0x2aa22103e52, 0x0, 0xc0003fa480)
	/home/buildozer/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:544 +0x78
github.com/etcd-io/bbolt.(*DB).View(0x0, 0xc000415d60, 0x0, 0x0)
	/home/buildozer/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:709 +0x3a
github.com/aquasecurity/trivy-db/pkg/db.Config.get(0x2aa227eb574, 0x5, 0x2aa227ed5be, 0x8, 0x2aa227ea79e, 0x4, 0x0, 0x0, 0x0, 0x2aa22db09a0, ...)
	/home/buildozer/go/pkg/mod/github.com/aquasecurity/trivy-db@v0.0.0-20191226181755-d6cabf5bc5d1/pkg/db/db.go:154 +0x8a
github.com/aquasecurity/trivy-db/pkg/db.Config.GetMetadata(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00043efc0, 0xc00043efd0)
	/home/buildozer/go/pkg/mod/github.com/aquasecurity/trivy-db@v0.0.0-20191226181755-d6cabf5bc5d1/pkg/db/db.go:97 +0x7c
github.com/aquasecurity/trivy/pkg/rpc/server.Test_dbWorker_update.func1(0xc000182b00)
	/builds/TBK/aports/testing/trivy/src/src/github.com/aquasecurity/trivy/pkg/rpc/server/listen_test.go:150 +0x6b4
testing.tRunner(0xc000182b00, 0xc000592920)
	/usr/lib/go/src/testing/testing.go:909 +0xd6
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:960 +0x36c
FAIL	github.com/aquasecurity/trivy/pkg/rpc/server	0.203s
```
Full log - https://gitlab.alpinelinux.org/TBK/aports/-/jobs/62487/raw

**Comment by simar7** [comment]
Hi @TBK, thank you for reporting this. Sorry that you had to run into this. Could you describe what commit/revision of Trivy you were working with at the moment when you saw this panic? And to clarify, this is running on a s390x that's running Linux? What Linux distro/kernel is that?

**Comment by TBK** [comment]
Sorry, forgot to include the version info. It was v0.5.2.

It is our (Alpine Linux's) CI environment. It is running on Alpine Linux edge, kernel version 5.4.35.

I just tested locally using qemu-static and the issue still persists with v0.6.0.

**Comment by simar7** [comment]
Thanks @TBK for the input. We'll take a look at it soon.

**Comment by simar7** [comment]
Hi @TBK thanks for the wait. I've indeed confirmed this is an issue and found why it happens. Turns out BoltDB databases are architecture dependent and not portable. In other words, you cannot take a database file built on an x86 machine (little endian) and use it in a s390x machine (big endian). All our Trivy DB's are built on a x86 CI.

You can find more info here https://github.com/boltdb/bolt/blob/master/README.md#caveats--limitations 

Let us know if that helps!
